apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actual-budget
  namespace: flux-system
spec:
  releaseName: actual-budget
  targetNamespace: actual-budget
  values:
    image: docker.io/actualbudget/actual-server:26.8.1@sha256:6478d9ddfc0924479c09e6699c205e354c6f2216dfe7de3c0fb7b590d6edcdc5
    port: 5006
    hostname: budget.greedo.net
    strategy: Recreate
    resources:
      requests:
        memory: 32Mi
      limits:
        memory: 128Mi
    livenessProbe:
      httpGet:
        path: /
        port: 5006
      initialDelaySeconds: 15
      periodSeconds: 30
      failureThreshold: 3
    env:
      TZ: "Europe/Amsterdam"
    persistence:
      enabled: true
      size: 100Mi
      mountPath: /data
    securityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
