apiVersion: batch/v1
kind: CronJob
metadata:
  name: cullarr
  namespace: cullarr
spec:
  schedule: "0 3 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: cullarr
              image: ghcr.io/bvdwalt/cullarr:0.4.3@sha256:dbf1f82a7f0aa2db8ad3fab44334264b94b66bf0d135358c0836037cfec6a056
              env:
                - name: CULLARR_JELLYFIN_URL
                  value: http://jellyfin.jellyfin.svc.cluster.local
                - name: CULLARR_SONARR_URL
                  value: http://sonarr.downloads.svc.cluster.local
                - name: CULLARR_SONARR_ENABLED
                  value: "true"
                - name: CULLARR_SONARR_UNMONITOR
                  value: "true"
                - name: CULLARR_RADARR_URL
                  value: http://radarr.downloads.svc.cluster.local
                - name: CULLARR_RADARR_ENABLED
                  value: "true"
                - name: CULLARR_RADARR_REMOVE
                  value: "true"
                - name: CULLARR_DRY_RUN
                  value: "false"
                - name: TZ
                  value: Africa/Johannesburg
              envFrom:
                - secretRef:
                    name: cullarr
              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                runAsUser: 65532
                runAsGroup: 65532
                capabilities:
                  drop: ["ALL"]
                seccompProfile:
                  type: RuntimeDefault
              resources:
                requests:
                  cpu: 25m
                  memory: 64Mi
                limits:
                  cpu: 250m
                  memory: 256Mi
