theme:
  background-color: 240 21 15
  contrast-multiplier: 1.2
  primary-color: 217 92 83
  positive-color: 115 54 76
  negative-color: 347 70 65

pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: clock
            hour-format: 24h
            timezones:
              - timezone: Africa/Johannesburg
                label: Cape Town
              - timezone: Asia/Dubai
                label: Dubai
              - timezone: UTC
                label: UTC

          - type: calendar
            first-day-of-week: monday

          - type: search
            search-engine: https://www.ecosia.org/search?q={QUERY}
            new-tab: true

          - type: to-do

          - type: bookmarks
            groups:
              - title: Developer
                links:
                  - title: GitHub
                    url: https://github.com/
              - title: Social
                links:
                  - title: Reddit
                    url: https://reddit.com/
                  - title: YouTube
                    url: https://youtube.com/

      - size: full
        widgets:
          - type: server-stats
            servers:
              - type: local
                name: Altair
                mountpoints:
                  "/":
                    name: Root

          - type: dns-stats
            service: adguard
            url: http://adguard.adguard.svc.cluster.local
            username: ${ADGUARD_USERNAME}
            password: ${ADGUARD_PASSWORD}
            hour-format: 24h

          - type: monitor
            title: Services
            sites:
              - title: Jellyfin
                url: https://jellyfin.greedo.net
                icon: si:jellyfin
              - title: Jellyseerr
                url: https://seerr.greedo.net
                icon: si:jellyfin
              - title: Sonarr
                url: https://sonarr.greedo.net
                icon: si:sonarr
              - title: Radarr
                url: https://radarr.greedo.net
                icon: si:radarr
              - title: Navidrome
                url: https://navidrome.greedo.net
                icon: si:navidrome
              - title: ActualBudget
                url: https://budget.greedo.net
                icon: si:actualbudget
              - title: Gitea
                url: https://gitea.greedo.net
                icon: si:gitea
              - title: Linkwarden
                url: https://linkwarden.raspi.greedo.net
              - title: Bazarr
                url: https://bazarr.greedo.net
              - title: Prowlarr
                url: https://prowlarr.greedo.net
              - title: qBittorrent
                url: https://downloads.greedo.net
                icon: si:qbittorrent
              - title: Lidarr
                url: https://lidarr.greedo.net
              - title: slskd
                url: https://slskd.greedo.net
              - title: Beszel
                url: https://beszel.raspi.greedo.net
              - title: Vaultwarden
                url: https://vw.greedo.net
                icon: si:vaultwarden
              - title: Pocket-ID
                url: https://pocketid.greedo.net
              - title: Proxmox
                url: https://pve.greedo.net
                icon: si:proxmox
              - title: Traefik (Altair)
                url: https://traefik.greedo.net
                icon: si:traefikproxy
              - title: Traefik (Raspi)
                url: https://traefik.raspi.greedo.net
                icon: si:traefikproxy
              - title: AdGuard Home
                url: https://adguard.greedo.net
                icon: si:adguard
              - title: Grafana
                url: https://grafana.greedo.net
                icon: si:grafana
              - title: Backrest
                url: https://backrest.greedo.net
              - title: IT Tools
                url: https://ittools.greedo.net
              - title: Overdrive
                url: https://overdrive.greedo.net
              - title: Metering
                url: https://metering.greedo.net
              - title: Music Grabber
                url: https://musicgrabber.greedo.net

  - name: Dev
    columns:
      - size: full
        widgets:
          - type: releases
            show-source-icon: true
            collapse-after: 5
            repositories:
              - glanceapp/glance
              - jellyfin/jellyfin
              - Sonarr/Sonarr
              - Radarr/Radarr
              - lidarr/Lidarr
              - morpheus65535/bazarr
              - Prowlarr/Prowlarr
              - navidrome/navidrome
              - dani-garcia/vaultwarden
              - go-gitea/gitea
              - AdguardTeam/AdGuardHome
              - henrygd/beszel
              - garethgeorge/backrest
              - slskd/slskd

          - type: repository
            repository: bvdwalt/homelab
            pull-requests-limit: 5
            issues-limit: 5
            commits-limit: 5

