apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - whoami.yaml
  - downloads.yaml
  - postgresql.yaml
  - gitea.yaml
  - monitoring.yaml
  - seerr.yaml
  - navidrome.yaml
  - pinchflat.yaml
  - it-tools.yaml
  - jellystat.yaml
  - metering-dashboard.yaml
  - metering-api.yaml
  - actual-budget.yaml
  - atuin.yaml
  - overdrive.yaml
  - vaultwarden.yaml
  - pocket-id.yaml
  - cullarr.yaml
  - backrest.yaml
  - adguard.yaml
  - jellyfin.yaml
  - homepage.yaml
  - glance.yaml
  - inkbase.yaml
