---
apiVersion: v1
kind: Service
metadata:
  name: adguard-dns
  namespace: adguard
spec:
  type: LoadBalancer
  loadBalancerClass: io.cilium/node
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: adguard
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
