apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pinchflat
  namespace: flux-system
spec:
  releaseName: pinchflat
  targetNamespace: pinchflat
  values:
    image: ghcr.io/kieraneglin/pinchflat:v2025.6.6@sha256:4e975edf58f0861a5cbfe8fc6aac4851ff5a02dfc3f05ffeea4982e3084a5a4a
    port: 8945
    hostname: pinchflat.greedo.net
    resources:
      requests:
        memory: 128Mi
      limits:
        memory: 1Gi
    livenessProbe:
      httpGet:
        path: /
        port: 8945
      initialDelaySeconds: 15
      periodSeconds: 30
      failureThreshold: 3
    env:
      TZ: Europe/Amsterdam
    persistence:
      enabled: true
      mountPath: /config
      size: 1Gi
    hostPaths:
      - name: tube
        hostPath: /mnt/media/tube
        mountPath: /downloads
    securityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
