apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: palimpsest
  namespace: flux-system
spec:
  releaseName: palimpsest
  targetNamespace: palimpsest
  values:
    image: ghcr.io/bvdwalt/palimpsest:0.7.0@sha256:5baabd6131ab2c3a6ecb59ca800b6c0a5014684e45fc55695885af6b26f6d5af
    port: 8080
    hostname: notes.greedo.net
    bypassOidcPathPrefix: /api
    bypassOidcExceptPath: /api/config
    resources:
      requests:
        memory: 32Mi
      limits:
        memory: 128Mi
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 30
      failureThreshold: 3
    persistence:
      enabled: true
      size: 500Mi
      mountPath: /data
    securityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
