apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: palimpsest
  namespace: flux-system
spec:
  releaseName: palimpsest
  targetNamespace: palimpsest
  values:
    image: ghcr.io/bvdwalt/palimpsest:0.6.0@sha256:417095d939cd5a3470a910209143274b9490d5f5eaa01a28a066a22ea529eaa1
    port: 8080
    hostname: notes.greedo.net
    resources:
      requests:
        memory: 32Mi
      limits:
        memory: 128Mi
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 30
      failureThreshold: 3
    persistence:
      enabled: true
      size: 500Mi
      mountPath: /data
    securityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
