apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whoami
  namespace: flux-system
spec:
  releaseName: whoami
  targetNamespace: whoami
  values:
    image: traefik/whoami:v1.11.0@sha256:c2c89736959e8830c3db090e2f54500499ceb0460267f91dce494728d7327770
    port: 8080
    hostname: whoami.raspi.greedo.net
    resources:
      requests:
        memory: 8Mi
      limits:
        memory: 32Mi
    env:
      WHOAMI_PORT_NUMBER: "8080"
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 30
      failureThreshold: 3
    securityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
