apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whoami
  namespace: flux-system
spec:
  releaseName: whoami
  targetNamespace: whoami
  values:
    image: traefik/whoami:v1.12.0@sha256:fb8458a97e9695115b0367e5ecf2a1a72de48b306acccccd01455b46334d2300
    port: 8080
    hostname: whoami.raspi.greedo.net
    resources:
      requests:
        memory: 8Mi
      limits:
        memory: 32Mi
    env:
      WHOAMI_PORT_NUMBER: "8080"
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 30
      failureThreshold: 3
    securityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
