---
- datetime:
    text_size: 4xl
    format:
      dateStyle: long
      timeStyle: short
      hour12: true

- greeting:
    text_size: xl
    text: Welcome to my Homepage

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank

- openweathermap:
    units: metric
    provider: openweathermap
    apiKey: "{{HOMEPAGE_VAR_OPENWEATHERMAP_KEY}}"
    cache: 30
    format:
      maximumFractionDigits: 2
