apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dlq-processor
  namespace: flux-system
spec:
  releaseName: dlq-processor
  targetNamespace: order-pipeline
  values:
    image: ghcr.io/bvdwalt/order-pipeline/dlq-processor:0.2.0@sha256:ad35d0a54d0aa5b12304b03e32b43afe4b6ab00f306076b77fba8aef70d67d54
    imagePullSecrets:
      - ghcr-pull-secret
    port: 8080
    env:
      POSTGRES_HOST: "postgresql.postgresql.svc.cluster.local"
      POSTGRES_USER: "dlq_service"
      POSTGRES_DB: "order_pipeline"
    existingSecret: order-pipeline-dlq-processor-postgres
    resources:
      requests:
        memory: 32Mi
      limits:
        memory: 128Mi
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 6
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 30
      failureThreshold: 3
    securityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      readOnlyRootFilesystem: true
