apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: inventory-service
  namespace: flux-system
spec:
  releaseName: inventory-service
  targetNamespace: order-pipeline
  values:
    image: ghcr.io/bvdwalt/order-pipeline/inventory-service:0.2.1@sha256:533fb8980e92a79aa8676ac59089fa7c721c0fb4d27763d467d8450c21fb4e6c
    imagePullSecrets:
      - ghcr-pull-secret
    replicas: 2
    port: 8080
    resources:
      requests:
        memory: 32Mi
      limits:
        memory: 128Mi
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 6
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 30
      failureThreshold: 3
    securityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      readOnlyRootFilesystem: true
