apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: inventory-service
  namespace: flux-system
spec:
  releaseName: inventory-service
  targetNamespace: order-pipeline
  values:
    image: ghcr.io/bvdwalt/order-pipeline/inventory-service:0.3.4@sha256:1f510694a897a38e84309a07c8ad5bd88b4029e505af6b5202d275c23f7e217c
    imagePullSecrets:
      - ghcr-pull-secret
    replicas: 2
    port: 8080
    env:
      POSTGRES_HOST: "postgresql.postgresql.svc.cluster.local"
      POSTGRES_USER: "inventory_service"
      POSTGRES_DB: "order_pipeline"
    existingSecret: order-pipeline-inventory-postgres
    resources:
      requests:
        memory: 32Mi
      limits:
        memory: 128Mi
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 6
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 30
      failureThreshold: 3
    securityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      readOnlyRootFilesystem: true
