apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: notification-service
  namespace: flux-system
spec:
  releaseName: notification-service
  targetNamespace: order-pipeline
  values:
    image: ghcr.io/bvdwalt/order-pipeline/notification-service:0.2.1@sha256:0fb0f82e086c376a236de434d488ddc00cec3a426d679d82597d445a0aaf4b2c
    imagePullSecrets:
      - ghcr-pull-secret
    port: 8080
    env:
      POSTGRES_HOST: "postgresql.postgresql.svc.cluster.local"
      POSTGRES_USER: "notification_service"
      POSTGRES_DB: "order_pipeline"
    existingSecret: order-pipeline-notification-postgres
    resources:
      requests:
        memory: 32Mi
      limits:
        memory: 128Mi
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 6
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 30
      failureThreshold: 3
    securityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      readOnlyRootFilesystem: true
