apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: shipping-service
  namespace: flux-system
spec:
  releaseName: shipping-service
  targetNamespace: order-pipeline
  values:
    image: ghcr.io/bvdwalt/order-pipeline/shipping-service:0.8.0@sha256:4e7d30e93322249940595dd4fec333ab5c81706b7d59fc484d35f60081b9533a
    imagePullSecrets:
      - ghcr-pull-secret
    port: 8080
    env:
      POSTGRES_HOST: "postgresql.postgresql.svc.cluster.local"
      POSTGRES_USER: "shipping_service"
      POSTGRES_DB: "order_pipeline"
    existingSecret: order-pipeline-shipping-postgres
    resources:
      requests:
        memory: 32Mi
      limits:
        memory: 128Mi
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 6
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 30
      failureThreshold: 3
    securityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      readOnlyRootFilesystem: true
