---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: gitea-receiver
  namespace: flux-system
spec:
  type: generic
  events:
    - push
  secretRef:
    name: flux-receiver-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: flux-system
      namespace: flux-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-proxy
  namespace: flux-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-proxy
  template:
    metadata:
      labels:
        app: webhook-proxy
    spec:
      hostNetwork: true
      containers:
        - name: socat
          image: alpine/socat:latest
          args:
            - TCP4-LISTEN:31901,fork,reuseaddr
            - TCP4:10.109.151.25:80
