---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: gitea-receiver
  namespace: flux-system
spec:
  type: generic-hmac
  events:
    - push
  secretRef:
    name: flux-receiver-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: flux-system
      namespace: flux-system
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-receiver-nodeport
  namespace: flux-system
spec:
  type: NodePort
  selector:
    app: notification-controller
  ports:
    - port: 80
      targetPort: http-webhook
      nodePort: 31900
