---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: gitea-receiver
  namespace: flux-system
spec:
  type: github
  events:
    - push
  secretRef:
    name: flux-receiver-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: flux-system
      namespace: flux-system
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: flux-webhook-receiver
  namespace: flux-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`flux-webhook.greedo.net`) && PathPrefix(`/hook/`)
      kind: Rule
      services:
        - name: webhook-receiver
          port: 9292
  tls: {}
