apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id
  namespace: flux-system
spec:
  releaseName: pocket-id
  targetNamespace: pocket-id
  values:
    image: ghcr.io/pocket-id/pocket-id:v2.17.0@sha256:19f556d5852115c8ebbef271f6f7cf610d8803312a1fa63f29e1b342fe9d2939
    port: 1411
    hostname: pocketid.greedo.net
    strategy: Recreate
    priorityClassName: system-cluster-critical
    resources:
      requests:
        memory: 16Mi
      limits:
        memory: 64Mi
    livenessProbe:
      httpGet:
        path: /
        port: 1411
      initialDelaySeconds: 30
      periodSeconds: 30
      failureThreshold: 3
    env:
      APP_URL: "https://pocketid.greedo.net"
      TRUST_PROXY: "true"
      TZ: "Africa/Johannesburg"
    middlewares: []
    existingSecret: pocket-id-secrets
    persistence:
      enabled: true
      size: 100Mi
      mountPath: /app/data
    securityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 3004
      runAsGroup: 3004
      readOnlyRootFilesystem: true
