apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: crowdsec
spec:
  interval: 30m
  chart:
    spec:
      chart: crowdsec
      version: "0.24.0"
      sourceRef:
        kind: HelmRepository
        name: crowdsec
        namespace: flux-system
      interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: crowdsec-appsec
            patch: |-
              - op: replace
                path: /spec/template/spec/volumes/1
                value:
                  name: crowdsec-config
                  hostPath:
                    path: /var/lib/crowdsec-appsec-config
                    type: DirectoryOrCreate
              - op: replace
                path: /spec/template/spec/initContainers/0/command/2
                value: |-
                  if [ -f /tmp_config/local_api_credentials.yaml ]; then echo "credentials already present, skipping registration"; else until nc "$LAPI_HOST" "$LAPI_PORT" -z; do echo waiting for lapi to start; sleep 5; done; ln -s /staging/etc/crowdsec /etc/crowdsec && cscli lapi register --machine "$USERNAME" -u "$LAPI_URL" --token "$REGISTRATION_TOKEN" && cp /etc/crowdsec/local_api_credentials.yaml /tmp_config/local_api_credentials.yaml; fi
  values:
    container_runtime: containerd
    lapi:
      env:
        - name: BOUNCER_KEY_traefik
          valueFrom:
            secretKeyRef:
              name: crowdsec-keys
              key: BOUNCER_KEY_traefik
    agent:
      acquisition:
        - namespace: kube-system
          podName: "traefik-*"
          program: traefik
      env:
        - name: COLLECTIONS
          value: "crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/base-http-scenarios"
    appsec:
      enabled: true
      acquisitions:
        - source: appsec
          listen_addr: "0.0.0.0:7422"
          path: /
          appsec_config: crowdsecurity/appsec-default
          labels:
            type: appsec
      env:
        - name: COLLECTIONS
          value: "crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules"
