apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: crowdsec
spec:
  interval: 30m
  chart:
    spec:
      chart: crowdsec
      version: "0.24.0"
      sourceRef:
        kind: HelmRepository
        name: crowdsec
        namespace: flux-system
      interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    container_runtime: containerd
    config:
      postoverflows:
        s01-whitelist:
          lan-whitelist.yaml: |
            name: crowdsecurity/lan-whitelist
            description: "Whitelist local LAN traffic"
            whitelist:
              reason: "Local LAN (Altair)"
              cidr:
                - "10.13.1.0/24"
    lapi:
      env:
        - name: BOUNCER_KEY_traefik
          valueFrom:
            secretKeyRef:
              name: crowdsec-keys
              key: BOUNCER_KEY_traefik
    agent:
      acquisition:
        - namespace: kube-system
          podName: "traefik-*"
          program: traefik
      env:
        - name: COLLECTIONS
          value: "crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/base-http-scenarios"
