image: ""
port: 80
hostname: ""
strategy: RollingUpdate

middlewares:
  - name: oidc-auth
    namespace: kube-system

args: []
env: {}
existingSecret: ""
extraSecrets: []

resources: {}
livenessProbe: {}

persistence:
  enabled: false
  size: 100Mi
  mountPath: /data
  storageClass: local-path

securityContext:
  enabled: true
  privileged: false
  runAsNonRoot: false
  runAsUser: null
  runAsGroup: null
  capabilities:
    add: []

configFiles: {}
existingConfigMap: ""
configKeys: []
configMountPath: ""

initContainers: []
extraContainers: []

hostNetwork: false
priorityClassName: ""

hostPaths: []

podAnnotations:
  reloader.stakater.com/auto: "true"
# - name: pvcs
#   hostPath: /var/lib/rancher/k3s/storage
#   mountPath: /pvcs
#   readOnly: true
