image: ""
port: 80
hostname: ""
strategy: RollingUpdate

args: []
env: {}
existingSecret: ""

persistence:
  enabled: false
  size: 100Mi
  mountPath: /data
  storageClass: local-path

securityContext:
  enabled: true
  runAsNonRoot: false
  runAsUser: null
  runAsGroup: null
  capabilities:
    add: []

configFiles: {}
existingConfigMap: ""
configKeys: []
configMountPath: ""

initContainers: []

hostNetwork: false

hostPaths: []
# - name: pvcs
#   hostPath: /var/lib/rancher/k3s/storage
#   mountPath: /pvcs
#   readOnly: true
