apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: navidrome
  namespace: flux-system
spec:
  releaseName: navidrome
  targetNamespace: navidrome
  values:
    image: deluan/navidrome:0.63.2@sha256:38246ebb80d6f7e2724eecab4acafa7b14ec66ae800b2454aa6da4c19f80a9ce
    port: 4533
    hostname: navidrome.greedo.net
    strategy: Recreate
    resources:
      requests:
        memory: 64Mi
      limits:
        memory: 256Mi
    livenessProbe:
      httpGet:
        path: /
        port: 4533
      initialDelaySeconds: 15
      periodSeconds: 30
      failureThreshold: 3
    middlewares: []
    env:
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      TZ: Europe/Amsterdam
    persistence:
      enabled: true
      mountPath: /data
      size: 1Gi
    hostPaths:
      - name: music
        hostPath: /mnt/media/music
        mountPath: /music
