apiVersion: batch/v1
kind: CronJob
metadata:
  name: cullarr
  namespace: cullarr
spec:
  schedule: "0 3 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cullarr
              image: ghcr.io/bvdwalt/cullarr:0.4.1@sha256:0b5d3c5623f0b647cae901d869e934db1f1105f9c75b727644a1bcc49e3dd6da
              env:
                - name: CULLARR_JELLYFIN_URL
                  value: http://jellyfin.jellyfin.svc.cluster.local:8096
                - name: CULLARR_SONARR_URL
                  value: http://sonarr.downloads.svc.cluster.local
                - name: CULLARR_SONARR_ENABLED
                  value: "true"
                - name: CULLARR_SONARR_UNMONITOR
                  value: "true"
                - name: CULLARR_RADARR_URL
                  value: http://radarr.downloads.svc.cluster.local
                - name: CULLARR_RADARR_ENABLED
                  value: "true"
                - name: CULLARR_RADARR_REMOVE
                  value: "true"
                - name: CULLARR_DRY_RUN
                  value: "false"
                - name: TZ
                  value: Europe/Amsterdam
              envFrom:
                - secretRef:
                    name: cullarr
              resources:
                requests:
                  cpu: 25m
                  memory: 64Mi
                limits:
                  memory: 256Mi
