apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  interval: 10m
  releaseName: jellyfin
  targetNamespace: jellyfin
  install:
    createNamespace: true
  chart:
    spec:
      chart: ./k8s/charts/homelab-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    image: lscr.io/linuxserver/jellyfin:10.11.11
    port: 8096
    hostname: jellyfin.greedo.net
    strategy: Recreate
    resources:
      requests:
        memory: 256Mi
      limits:
        memory: 1Gi
    livenessProbe:
      httpGet:
        path: /
        port: 8096
      initialDelaySeconds: 60
      periodSeconds: 30
      failureThreshold: 3
    env:
      PUID: "1000"
      PGID: "993"
      TZ: Europe/Amsterdam
    persistence:
      enabled: true
      mountPath: /config
      size: 10Gi
    hostPaths:
      - name: dri
        hostPath: /dev/dri
        mountPath: /dev/dri
      - name: shows
        hostPath: /mnt/media/shows
        mountPath: /shows
      - name: movies
        hostPath: /mnt/media/movies
        mountPath: /movies
      - name: music
        hostPath: /mnt/media/music
        mountPath: /music
    securityContext:
      enabled: false
