apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - whoami.yaml
  - adguard.yaml
  - jellyfin.yaml
  - seerr.yaml
  - navidrome.yaml
  - downloads
configMapGenerator:
  - name: adguard-config
    namespace: adguard
    options:
      disableNameSuffixHash: true
    files:
      - adguard-config/AdGuardHome.yaml
