apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - adguard.yaml
  - adguard.sops.yaml
  - adguard-dns-service.yaml
  - jellyfin.yaml
  - homepage.yaml
  - glance.yaml
configMapGenerator:
  - name: homepage-config
    namespace: homepage
    options:
      disableNameSuffixHash: true
    files:
      - homepage-config/settings.yaml
      - homepage-config/bookmarks.yaml
      - homepage-config/widgets.yaml
      - homepage-config/services.yaml
      - homepage-config/kubernetes.yaml
      - homepage-config/docker.yaml
      - homepage-config/custom.css
      - homepage-config/custom.js
  - name: glance-config
    namespace: glance
    options:
      disableNameSuffixHash: true
    files:
      - glance-config/glance.yml
  - name: adguard-config
    namespace: adguard
    options:
      disableNameSuffixHash: true
    files:
      - adguard-config/AdGuardHome.yaml
