apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- infrastructure-secrets.yaml
- infrastructure-sources.yaml
- infrastructure-releases.yaml
- infrastructure-configs.yaml
- apps/
patches:
- path: kustomize-controller-tuning.yaml
  target:
    kind: Deployment
    name: kustomize-controller
