apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: beszel-agent
  namespace: flux-system
spec:
  releaseName: beszel-agent
  targetNamespace: beszel
  install:
    createNamespace: false
  values:
    image: henrygd/beszel-agent:0.18.8@sha256:3b1939746690e423072b4a99bf4c4af6dd9562a68978a33738a3c4a4cc000c39
    port: 45876
    strategy: Recreate
    resources:
      requests:
        memory: 16Mi
      limits:
        memory: 32Mi
    readinessProbe:
      tcpSocket:
        port: 45876
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 6
    livenessProbe:
      tcpSocket:
        port: 45876
      initialDelaySeconds: 15
      periodSeconds: 30
      failureThreshold: 3
    hostNetwork: true
    env:
      LISTEN: ":45876"
      TZ: Africa/Johannesburg
      HUB_URL: https://beszel.raspi.greedo.net
    existingSecret: beszel-agent
    securityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      readOnlyRootFilesystem: true
