apiVersion: v1
kind: Secret
metadata:
    name: backrest
    namespace: backrest
stringData:
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:DdRuzAF1,iv:mjcO4T3/mnbwe8mw2fG9Yg00eKDr6SYVXIRuYm10qwo=,tag:kLoqs7RgfuaJEq6SRJG5nA==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:6gFZRsSFRtNKPpZPnG5F,iv:sVpS4FoZiHRsgLqorPAcGxm3VIeCR0wnW1Zm/+vT138=,tag:vY0UDKkm707IIT2gzAhV9Q==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:DeVG9aMaR1ENe5uAOL/aLuuOnXDWsfZ0exPsYLpfhkmn8AEU++WLFzxGYKWOtskjG55FbVhMSFg73k2a2/bdvMTY2WCGfMMNDOQkZCEYa04ZhE7N04ldYR/f5btUagj/EIYJPyJ2/kIqGyfK7nnqBIn6rfvazMKOh0O+eQ==,iv:5oFDuCoi44L+c6UKIeQQvq+8j4x+47JCPZtKPsugQh8=,tag:6Hx6MQXjniMuvHg9p2W3xA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:bUWJh2cNotHxluUgcqhCpuzmpn7CAtlLlIWsGBE=,iv:Ta5Bnhe9YDkQev7kUA3YyKO6ws07z6vO3ahlrmicM8k=,tag:Sa1aqbbv/ONtVlNE1qGPVw==,type:str]
    BACKREST_ADMIN_PASSWORD_BCRYPT: ENC[AES256_GCM,data:i/2gzlwgKLVIDY8BCaLKQ1uDxIxukAhi4BKscB5gqIg+bKmHK838uhEjiMNBYYfQuOSmJXQp0rG2LQI20AGUO6KJq7ouWkSZYgS1vIrZU2w=,iv:ii+1PwXipmvn3FTqtFZvqi3VJpPPC+x14PtzI5LaNN8=,tag:JXjr+zHjhPlEA21gJ5/1+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUXFGS04zaDh0T05LQUcz
            UnFpNXRJY05kNW5oRVZXUGNDZVo0TVE5YURvCm1xQ3k1RXBzd0RXVTdWTDNvaWR6
            dGxVVUtGQWVYR1RJNFkzY2JNbXBCQ2MKLS0tIHJsQk1qeXFwcVZMYmUrajhrRTNH
            QzRKZVhyc3F0cDV6bnhrMDZ2NG1keEEK+9G8XdgRE3/WD+awsIc/8V7j9Ktpc58V
            AKVyyFa14yKE6JZ+IItFB1HSLtjYcyz8k90JxDFxkE+dMsqERWbCWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-08T15:16:33Z"
    mac: ENC[AES256_GCM,data:5PWfyhnzc8+jVSB77OYkXlh8xB9THvQH8JGUARk5bJ2XMI0uSVN6vrAeulkgNwdDVTBBdAk0TRYxWaPIfSGUaUyhvZGy8nCiDLotSDwrT137vTZL45uxBIat5LxZkV57kDPZsDwEJ9prnD7aPSrn1oF+zIstoi7JlxtzSUGytiM=,iv:1x/qGyb6kN4cEkRq0+AYDQtxuFevxsCvm1JsK03Dda4=,tag:AaF0/yClEgC3A90eAJUfsw==,type:str]
    version: 3.13.1
