apiVersion: v1
kind: Secret
metadata:
    name: backrest
    namespace: backrest
stringData:
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:DdRuzAF1,iv:mjcO4T3/mnbwe8mw2fG9Yg00eKDr6SYVXIRuYm10qwo=,tag:kLoqs7RgfuaJEq6SRJG5nA==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:6gFZRsSFRtNKPpZPnG5F,iv:sVpS4FoZiHRsgLqorPAcGxm3VIeCR0wnW1Zm/+vT138=,tag:vY0UDKkm707IIT2gzAhV9Q==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:3bOdr64AUfXG1OelAYBswwPy6Way4ekpViH3fYc/Qi1LxhjAeL62P4G21alAa5KGoQSU,iv:III3olKGmfIjbWnOF/ZBIAjvlGh9stPzPpbHDMZ3SSo=,tag:fJzx583HuCKeFnzmpb5lmA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUXFGS04zaDh0T05LQUcz
            UnFpNXRJY05kNW5oRVZXUGNDZVo0TVE5YURvCm1xQ3k1RXBzd0RXVTdWTDNvaWR6
            dGxVVUtGQWVYR1RJNFkzY2JNbXBCQ2MKLS0tIHJsQk1qeXFwcVZMYmUrajhrRTNH
            QzRKZVhyc3F0cDV6bnhrMDZ2NG1keEEK+9G8XdgRE3/WD+awsIc/8V7j9Ktpc58V
            AKVyyFa14yKE6JZ+IItFB1HSLtjYcyz8k90JxDFxkE+dMsqERWbCWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T14:45:14Z"
    mac: ENC[AES256_GCM,data:IChPneVB8Gdvf01ggOO3YynEvsoV2e2M+BKbAsEg+lQn/BDstYFj5qvxqNCaKlLCD1i4XgT+qIxSIbIxJNO2YxJDoQgvQ9jGPa+WETiR453cuQIoCKVBEeyWgKzM6CGmPV4q8kE3QDaMw8x0obfS05s98ZP60L3dIlNEccHIYgM=,iv:H9adLO57l5JXvw38ZLvN96PjqleTdwkVh50LY+VWdhQ=,tag:CaqI9BhAcCWrFmat21Mjaw==,type:str]
    version: 3.13.1
