apiVersion: v1
kind: Secret
metadata:
    name: beszel-agent
    namespace: beszel
stringData:
    KEY: ENC[AES256_GCM,data:mT1scEDNRr8OvIsSLRiemJzXH9DjT6MXJEQqn3XW6A36q6NSsDahRXQIO4tP+lpR5UdJ1IVCCvxaMbFC4woy+E10D2K6pM94ql3OVMsM1uA=,iv:UybrLK7FlzfqQV7jZ3YzDircBmlTK+5yfUQ2HGXCy9k=,tag:8csIdji99KEtHtbowKzwlg==,type:str]
    TOKEN: ENC[AES256_GCM,data:RmVdqXmreTgfn1VEEB9AJrJE/7PdRL/DxXJjB59T6GheNM9j,iv:t6uj+fKqo8F6UsbhIKqD7Cz4SHdDOWfp26M62sIPsyY=,tag:CwihINEV+2pskPrJP/Dl8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOHludXpkSnhwUlhsWUFn
            bmludG4wU1d1VlJKZjBYQzVpL0VhZG9hSkFjClZWbEU0UFZIblM3K0lwVE5xUUJE
            WVFjSUM4L2ZXQTdabUN3QlBtakk1ZHMKLS0tIDZjNEE0c2ZjTzRQenlQM3F3ejUy
            NVZIWmoxMTlyL3gzbWVZUzE3S25ReUUKep0907G++JTc+ucFNylUopQUwTlVbZ3M
            ocHOxOLeJpnA1dZGGtIfcnKbptXBryXtfQPiORomUcCS4hQRPgOnMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T09:59:35Z"
    mac: ENC[AES256_GCM,data:24dJAweb7UndY+smr9rWQE/PAI/Nx5POOlEd6w1KY2QDYruAvqX6oQHvzORlAOWHOndKl5ndEqadaR5JPwsoYyABrehlHsWPUCdDBOIdbz5d6ng74Y6N/rDp4GLmSf3ynGRblZu5wrq6eCeQ4uKv1L6xRBDjh9mLbqQXd+UKkI4=,iv:L/oVDLmaYaNQGyBP2+1NIQHNbf+108M8xjdhRhe7L1M=,tag:ClFcJsACVe2xUDyQb1KKTw==,type:str]
    version: 3.13.1
