apiVersion: v1
kind: Secret
metadata:
    name: beszel-agent
    namespace: beszel
stringData:
    KEY: ENC[AES256_GCM,data:Vrr1b3vLKuKhzv0D38kjK2UPAH6ORRxURAUS0J0w6AZx/st1dHFglIu4pvxndvWlxRZPwjZ3ABYV1HHU/RdZngmOKZD3wXponzxvSxbP3XE=,iv:4foe0z6YpZS3xOJOcyfZwgFLfcOezBV67dqZbheiTMA=,tag:zRVkNN+wcyNUTWa8Oq0A8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVlUvVi9ib3prRHMrZnFY
            YVBqbmNJdTE1L1lBdmVMTmpSNUdkdVhRZVcwCkZLeHhja2tucG5BOWhFQXh6RlpM
            NjRtc21ERk1GWGsxcHRUU1hMcm96OTAKLS0tIGFVMGVjK0RYVTBmamdGUloxRXh4
            SHBRWGVObGFnTHIyV1I5SlNEaTJtQ28KobuFoChO4XTwp3xaLKcAt0dEcWJAbqnG
            os2zhF6/i4Se1ZUScMofsFP14r5uE8tMHXucf+Vyvcqv7TtguAjRgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T09:49:07Z"
    mac: ENC[AES256_GCM,data:UarKmcYV8gBWiRn6R7bj8J/30rsREUr8OGdk4zrkM5t6kaS9H6s0Nq9WxaPIlMVZy6yuTIizHp2S2jxH0twne/hMgCggaz501ME/jG1QAplpfGoZdJhSz5iEKce9hyZ+eydcp/RX35xCSxDAuvm6eqmrlZgH1chytQ3oJ5bUaRo=,iv:2NjFry4YjMJ3XH0lcZkT8N1O8MYWmUTe8fLSk57wO8w=,tag:KlNLiwoSbnke/5AaDZTR9Q==,type:str]
    version: 3.13.1
