apiVersion: v1
kind: Secret
metadata:
    name: beszel-agent
    namespace: beszel
stringData:
    KEY: ENC[AES256_GCM,data:ha2SxXtAzbeTbyuKYGU/Rzn5EX4b15d5BOFzJL4BlGhM4t1xmbc/HAmdhusjcITdgEawyRE5sSILWYmbjclEndXKoXdIdFwmkD47JKiSb6g=,iv:rVuMm/3FU/hxvr5IWE4nKL/qFNr7MWlGZeGB/hXexSo=,tag:ig2yrX1HDfJtfLXzsEWHUw==,type:str]
    TOKEN: ENC[AES256_GCM,data:0FB2D+laCv4T9V1HMDOQC7aT2gZhlGYF/2AdCOF3kYPXVPDJ,iv:EAE85SMe8CTzvFgwciTgXpbRHS4X2pVf5TNPWvAoGU8=,tag:6BE0c7bNMQKpJvN0ZnM6vA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWWlJTHg5ZFlDR2d5NEND
            bnA2ZDdLaUxUQXpGeG55SjM2bUFGTUZkNUVjCnczUW5jUDVlcnE3ZWUrSmQ3VGpK
            eGdBSFVSMDlWT2xDbzFLSjBLejZoTk0KLS0tIGFEYm1EZC9qNGNvRkMrTmpUNkNC
            aWIveWRoWC9mVFRvRDZXellHcmo4T3cKvigddCksGHaGe3+RXGqFeY5Z6biEw3mG
            EP2riNQlBg1Th3kzqraRj6uu56uREy3n7Qfh9A/2qyBIM8MlVnTtOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T09:57:30Z"
    mac: ENC[AES256_GCM,data:ZuZkE3GAZYjtVgmKz0jUwjkgtMlYgtIyVbgyRxEg7lmWfv+zspywkpagZ8telyBtmO12NVIT8eNk/t05ZrBCmn//u9OvrcVRT+UmTMA+oEBzLfrtuyY0NGaKzi3N0vLGYCbSwyROJopVHQrbKQNzJ4UcIg3w1Gh5z8izGCc+idc=,iv:espHhGCDpOOXuXRQfGRdMhEXmFh0ck1VmiMjIxtWJOk=,tag:UL4MaI60w4O2Z8yIVlrZmg==,type:str]
    version: 3.13.1
