apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:uQcyH5uoUxxpEjYXH2qGf/spLdbRUI4uYydsbua82931f1EbAb3hWQ==,iv:gTcPtLNuSMHAo0Gtr9g/MjU8DQzlc/cmMaFvs8Lt6kY=,tag:oTtV2Z6q82NpPdms8KgYkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4blpJUkxHY2w0U05URXlk
            ZHpkWEdXcHRVRnNkemRONFhET1JCS2Q1aG5ZCmdvZVNMcFpaamRCK1BIN3VqSEc2
            SWk1QnBaSjl3VTFNdll0YXBvTW81MW8KLS0tIG5LZy81V2VWN2IxeGN5Qk52d3NR
            SnJzanAvalVCS3JxdUI4d2tGMnc1TU0KOtR5+0YEEHpl4bU8FyMMLN8DqM4bfuVP
            +KZVJnQj/qudMwAsGpdElC2yrjHlMg/iVSy0IDZ1/tTZpG0dH4Sulw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T15:10:41Z"
    mac: ENC[AES256_GCM,data:Tvcf5/Gc7QgeRwxKH1Yzup1CA6EnmEE/NSNgz4e0l+J33H9M8BrLGR3tmSRVEbomclPyVqzqs5jBaY05DH5TLRuT/bql7WC4OFSntxtMIcT78kO3xpJPOCtlQGN+DifeeAObQS4l6w5Vw91NDSku5cDP9DzyTjCdU5ZBwDOji5o=,iv:EKQySOCm40+J4wQyFhtZTvA/EZ6Q5Pg0KbL2FuY3u3A=,tag:cpG8YWhMZ9/N1ige2iCpeQ==,type:str]
    version: 3.13.1
