apiVersion: v1
kind: Secret
metadata:
    name: cullarr
    namespace: cullarr
stringData:
    CULLARR_JELLYFIN_APIKEY: ENC[AES256_GCM,data:6Vn4NDJbiSdJd4xgS4ww3emfEiL56bgURSUeAD3dYlg=,iv:934qzy97K6J2IGZMdjN+IDgF802kJzhRnIH+unCrEic=,tag:ZpjwGg94rNtxYN8SHJvvOA==,type:str]
    CULLARR_SONARR_APIKEY: ENC[AES256_GCM,data:lAWWxxlG2imyOf+GN6ZyEH/YmV/H9mS5wSVjcfFhTVM=,iv:vNgeJQoMOlUMO5IHWodZhAoMQPFB4K4xdOBu3hy9Daw=,tag:1vF9nL0M/4TGQHdCIwqllQ==,type:str]
    CULLARR_RADARR_APIKEY: ENC[AES256_GCM,data:Qri7ehviy5FgefhGIgH4favxl1S1ZK7kE3FXvmQ/1mI=,iv:Jy4Otbg2WUiCnXnvOrXqE3kOpXlfjcM3Wm9UCSzOHgk=,tag:QUbV27Go6lnkzqyQWOCcrg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbUpzOTNZblJVcDdwUm51
            TE5nK3JuSTNwS2IzVzNZdXY5VjZRQ0RrQUhzClBCVWl5bDFiSGszdjB6SW1tOVk5
            djU5QkdFeDVaQmJsWUlaTStzMDNnSGcKLS0tIG5rVkxJcjRhNmVLcHhMUlVnUVVs
            c1JiNFNyTGNXMVFqMlNmajdSVU44cnMKvzUohF3cc3qTZGudmS7mTxlZKQVdnXad
            pKMGh7Ku0CRVsvhUMVas/f11iY8kKR7dtuPfX1F2o658BNm2AP9nEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T07:01:56Z"
    mac: ENC[AES256_GCM,data:8i5DRwTWC7/3QeUTX/ceiQsiX/O82RjysB17lkrSnhyN0k3QV/axC/2ptokLsYhlSc6vKwfiL6cKFG3BJrAG1hF9P8hlkP/0MTUKwZ/4PsPPFEoXLhMNGn5PuiOPbwXBPjlxK+PXFknbaWwdlE5POnjypWjJpmLDmDwIHoxPCEU=,iv:VmBTk1JQDKOilKE4Oi7tqV3832i85vvpOQDqPtZZRUU=,tag:6+Jir9bXt8E8gDhjN5yCNg==,type:str]
    version: 3.13.1
