apiVersion: v1
kind: Secret
metadata:
    name: flux-github
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:GtxWSwMxqgMDysdA69f6jdaiohhosDLpto/bMBK8I6PJibrckwOCDimzwij3cLGzR6gB++Jp4RWgXHehE2/efq52e0AwER1u8SaTtlrK+3TpINWD/QhNoKaKw0dP,iv:F5u+ZDbqcUrnhOQGkVWVIoqjaQddLqdYAhWn0hz06G0=,tag:3GRGE+B/c2bkubbDjwRrLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSalNGM254THMzY3RxYTZX
            M2RhV2hZT2NYWDVQajdXaGYxNktMVWxlYWxvCnhhY1BmM1B1Y3pRUHBZNmo4dEhY
            Uy9yemgwVmlNM2FScFB6TEhQaUM0UGcKLS0tIHJ0SVJyMTF0cEZ2OUtuSU1FN0U5
            c0EycXlJMXRZNi9NUXdHQzBqVlhlQnMKvj0l3wFNV/+uXIhYYTbZTFfaJkoC5Oov
            f+1lBq5GNBx0pwjfJiKC7974IY5Wri+opAoQ8CtQ7sAPSF9stGqoeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T07:49:04Z"
    mac: ENC[AES256_GCM,data:6fyCDigk4DqZbwPSz8W47tTSCu5had002J5WOZPGMFl1mOtoIfjUFfAyPUwrByn9IhQy2hhS6ggedwLGo5Eh7gkIZGhb5pqbcIPD60tb5lt8h91AQQnglLRdWw7Q0XRmlCDlUkrtk1DB2z2dagr84GiCGJ/KgzSH9xVJRqv72vU=,iv:JDuLoSM3lgh4fmRHpIjCjPbIAiRARGhe9gMXI0DlshY=,tag:PfkYqH2ae3obkYpNEqzhew==,type:str]
    version: 3.13.2
