apiVersion: v1
kind: Secret
metadata:
    name: flux-ntfy
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:3CpQINuEycl6qpJPIdlBR7ns96BPDGyoYkvoU2MDCbBReEhBmVkkig==,iv:XrRf3iSHOgRCmHfcTliA7EccUqsyoVfmrif7tlEs6Gs=,tag:0FIxNle9Avdq0+nJuWvjqQ==,type:str]
    headers: ENC[AES256_GCM,data:UcB37DNPreYL32jFenKyx6KZjw56pWzO3CkgmyUCpss=,iv:vXRGdIcl9Cy7crgbC+TatQjkfJT41NqQMX3lPGspG/s=,tag:9FwWeADCSF/qNhQwVDsDFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT1BYVURwc3J4eDBtdnRM
            N3hWamNXVXB3SnpYVTRXMjNvUTlTQ1pUVzBzCjhhQnJBVmNwY3FhWmk3MjBQRG1J
            RFVIMVFINERiMzlVdlEwelZabzBnUmsKLS0tIExFaGM3d2puakFlb3NlT0l2RTdO
            L21aVUl4VjFzWWRUL3gwNDFiZnRaeDgKB995F6NPcErUU41P5FuzODtwhhC5h1Yi
            /H2mzlnRlA0PvuIesh9ZG23DD9FKQNg9UrhEZo+EXO2+Fz73L/iGSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T15:23:58Z"
    mac: ENC[AES256_GCM,data:rLvVc/n3B7i0dmqdIS9gljr5Bun4qot8rBA4Y6MxzPJEO/XuNb4Ygd/B1ciPiPUAAazD0jZ6kFcc1w2IM1ke71eZ0/hBh8Nh7Ru75r5oXANnSsHXH/VpSdDJUTu+Dg4JstrlVJUj8gywU2ULla3pllAMoIkggnei0XzNBJQB+y4=,iv:gfjFUEhU0XjJbZdAs2HyOm4sXJWnhgLm1paGQ1LR6es=,tag:r6LPPa7Aw20ER7Z9RHtlZg==,type:str]
    version: 3.13.2
