apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
stringData:
    HOMEPAGE_VAR_JELLYSEERR_KEY: ENC[AES256_GCM,data:tZFZzLqsyfLkl6kBcJybgS76expwDYX7EAPq9kTob1/drILrsLocqME9ckebk/VIaAcAM1DebvX5odYC3tczHa0utaA=,iv:B2/Z93O+z/E95g2RgZMBk+wG9iq5vxwY0nLXuD9XhPI=,tag:yX2d6CskPTTR5Z2C8nGxyw==,type:str]
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:/5fubE5JVawtEYHJEF08nwX8K3IXY/GKlB3F5JGwZXs=,iv:hWU82zFfU0fWWagvUbWRoCVGM2IXNWrIyIoXqokWJn0=,tag:Omv7wik931gYKwj1xzevuA==,type:str]
    HOMEPAGE_VAR_BAZARR_KEY: ENC[AES256_GCM,data:wDthNYuG/s72q+IDYAYpmJ+0h35LID0uFg+v2vh0ip4=,iv:hFtKwHyv34XHKMISgKNf4zlLJ4nbWzI285VC7FDMITY=,tag:8XYr9ansuBuu+510a3JehQ==,type:str]
    HOMEPAGE_VAR_TRUENAS_KEY: ENC[AES256_GCM,data:qIxt3L6hvTL/dNQ4rOe16g3t4RXv/9Am3bvj+OHkOYQnAr2Y2EI/Ci8Z6QHlwgw0ca0tyislToxxTMn1LciQZd3/,iv:0BHVfOzp9Rm/wnHEY+x0Rm4J7z+p3cej9AKi1iO+mkY=,tag:0Ljek0G0uTf6P9UZRa8Icw==,type:str]
    HOMEPAGE_VAR_OPENWEATHERMAP_KEY: ENC[AES256_GCM,data:pJEjRdIUBaqwypUgs2DzxjBV+37YxQVJ2iUe4xVVXt0=,iv:Nz/nex3gGCEJhDNs4mUOTpntG3t55+TTg87cSikOctw=,tag:ZElxwo4QXzdBTKvCDL1N8A==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:vaa9j1wq,iv:eTZZTAIxCLk8z5H9iJOK/9N+T1rhlxiAvwHCoGrC0og=,tag:Wb8QznANtRQ6YD5sW/Jjkg==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:YUboLR3DXk4aDqVbdcnGBzxBywBlV5r00H1j17U=,iv:LRP8nT09kFVNPgD5pjUnmiju2TuKuFym3k7w92iJxdY=,tag:xKNqh5t8G4LxHAIPVovFhw==,type:str]
    HOMEPAGE_VAR_SPEEDTEST_KEY: ENC[AES256_GCM,data:Xqv5Ga4c5qXx20uS5ALNze4yJEw3jm2YGDlQZk3UkiZwK9LeBOa5Yls3anu8AOLs,iv:2r8BDjY2YEKez++dMSrxnHNQcRofynWy2faYEF/wdiQ=,tag:9DQCvwd06hl2WG+vOO14nw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWWFkL0NTdU90R2pSS0o4
            bmFWakxYUUV0c2sxTkQ0RmQzbkpNejZGL2xJCkJDSmdYTnUzZXR2bksrMXZBZ1FW
            bCtxME50cE9vcXJocnRQUS9maUdlTlUKLS0tIEVvd2Y1NTlIRi9vdE43SVJPSXVC
            U1VnVTE4dXpxRG5CTUZoV3RiNlRTMEkKd92hqEx+AcJFC254zibK63Fqvvq9uJNv
            zHBtm4+fnT7E8EATD2tu3SvpMeXzCveZp8NeDOX8yZF3qBswZTFk1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T15:08:25Z"
    mac: ENC[AES256_GCM,data:N7tfHXJumfr+I4OBjjmKGunc+xqO647POEQS5cfeGQsfpRre7IaUpEd7KXTVe2UJvlHeSM3vURgyWNmu605jiB5EUdeYN4c0WqTwgMndGAxXyBu0H3jxIR8GxAeQql3F+38jgNHgwW8pNcqhlMB93DuK8Y6akngVy/ZP92Wmwa8=,iv:Xy7to3Qy2k52wbZy46yawEHW6ihWqRunpbrdczZ5OrI=,tag:kFuNe+sEm4qaYqMm0j1e4g==,type:str]
    version: 3.13.1
