apiVersion: ENC[AES256_GCM,data:9Tw=,iv:I2k7voR/Ff0FaHCLEaxdJI4C7yNImwuxk2xZWCDCSy8=,tag:cX0fyfyp+ifNhX3nk+XjpQ==,type:str]
kind: ENC[AES256_GCM,data:Yf9KPMaA,iv:kMp/dmJ2+b9HJCE//YSmuCqbVdcSFhzmzzDQMqF3qBw=,tag:eNZBE53U6MSJTXpJa+g4JQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Fvvcbt68/awnV/Ioss7AfQ==,iv:tQzkjl9TO0N/BOiSSOLXrwKdlHcsotKCVvokQkO7fvk=,tag:DIccJwy3K7HedPowjzq5Cg==,type:str]
    namespace: ENC[AES256_GCM,data:MNHNb56Gfn4=,iv:wRDOlMIgEW7Ip5416sKtCkluM1ESBQI/fHkOygAlNps=,tag:teiflZH1p8Z0V/jrTEumuQ==,type:str]
stringData:
    HOMEPAGE_VAR_JELLYSEERR_KEY: ENC[AES256_GCM,data:LanJ9V44mZ8N3z/ARiudKXViDdQvDRtcniAAsqUXHyiFXAlh91WfCu4ZeD+WRjy+DdddzZDiiGqZ+muJGffPA0rKmZs=,iv:7pPiYV3pVAdZYln6etwXPIlLXH7bQ9fHbMbFfBG5dv4=,tag:Edgb4wq0HdcJsXTo0d4QxQ==,type:str]
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:yjGw4phqqG7ZDw5eXKX9neSCIihVAX/X3U/PUcHFgS8=,iv:aCdkZQe0FN4T2NW1/JI+PpNbQpqfJk+rrnZEZYzMiRU=,tag:k7FEM3Gz8meRl9eOsgIW6A==,type:str]
    HOMEPAGE_VAR_BAZARR_KEY: ENC[AES256_GCM,data:6zspfnolneRyKVeBuDt807G+G3b9mAU+YxTSJfQtLbw=,iv:T46dZKE8JSSnUHJDSmisT7c8B0F8oZEaGjIjs5PSwqw=,tag:ECw4Ne7t8Xukr/BrwaOuSg==,type:str]
    HOMEPAGE_VAR_TRUENAS_KEY: ENC[AES256_GCM,data:hQcVlVzKZ7az7oUq45uDe8vaxy0XjVP/lvR8cd289O0BOiWmnVWR0LlLe8Gk9PhsheRQ/ZiDjDF05cKXF6Lv1x5p,iv:NdLJCm5Oi/0Ej+ptbL1uJIuhlCLcFaEmey+uwpr/nbA=,tag:zW3kc/+yV98s3Byunffqrg==,type:str]
    HOMEPAGE_VAR_OPENWEATHERMAP_KEY: ENC[AES256_GCM,data:lr5j80Xa0Bs/FGR952VV7an/BSr9ZlU2nI+FW6iB6M4=,iv:N/A/Q3sFApq7n5hdJm86lR6XisIBIfp/yoM5Z9CqpCs=,tag:RTB4jxpnQ3kNzuN39KN1Yw==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:sfjlZZRn,iv:f+08T8gHAFOQ9+x3nMNHBeYvBxwZ65A9CoGXMtVzsug=,tag:ZZYCylVSPCUN9KoxHKTylA==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:BjYB2VupZ0/MJQKkY+ZDQBxt09ltSxibK7jxEtM=,iv:vGU8T9pg6TZTtOVeJUcPvJ1v2Zlywvc4l0gLwd5z68c=,tag:HH3+N5AV3ffmfIaTlufYIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQjA5aUo3bEtWRWMxWC9o
            OThKaElvR3o3VkFjZTFubEl3YWg5R2cxbzM0CmdOeGtqTXgvUExYejRoekIvM3Yv
            VXJVYXUyMlQvTWFrNXp6M0xnU045YW8KLS0tIHFYS0Q0ZDd2QWJSYzVxQTQwcEM3
            bEQvdlQrMjBuNkI3T0FNdUhjNVFDZ3MK5ZgQhK7uADcLtFVbNIAgWUmyU6W7Sl+K
            hyBoBNcryudcLUNKYyR8G/5vzWXkIPQJWFGn0OCMrmZNX3GcrOuEqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    lastmodified: "2026-06-04T14:20:48Z"
    mac: ENC[AES256_GCM,data:RbHhpuFSEeqfj5xZ09WKeNGEPugCxtwRa9EKw9FZnBuRQp4bHlzarVhDdHRbcuFnTP31e9vpo1MsTZC1GcXlQ6hLJxlb/ifswOznLUyPFn+65ZtbLeM/bjTXI4VGzISnpMzE9P9ZlJ3sntj1uUeYxwtEM21U0sjLCjjh3407OG8=,iv:XLxiCCoMk8cd1zvLHyN6RaPAiMPvRd8cyBmtzgVtog8=,tag:hg1TIfFZEereDNm4BG3aRg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
