apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-namespace.yaml
  - cloudflare.sops.yaml
  - backrest-namespace.yaml
  - backrest.sops.yaml
  - beszel-namespace.yaml
  - beszel.sops.yaml
  - cullarr-namespace.yaml
  - cullarr.sops.yaml
  - pocket-id.sops.yaml
