apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare.sops.yaml
  - backrest.sops.yaml
  - beszel.sops.yaml
  - linkwarden.sops.yaml
  - oidc-auth.sops.yaml
  - flux-ntfy.sops.yaml
  - flux-github.sops.yaml
