apiVersion: v1
kind: Secret
metadata:
    name: linkwarden
    namespace: linkwarden
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:CwGcM5H+POJTwxsmWbIqCxtJA6VH9nKVelWUBdxRqFka+s0v4ZPT5f68Kg/b2eZqiABgUbq8IbO5WFgTKvKwSJ9ij33ZvHX+VZEPACyTyaXAWGt4D3YkylDhKQ==,iv:8dve7UsKxZjpuwThNQlwqsypwcBnvnee8MqVmUXTNUc=,tag:97qiK4rkmiiprCAEp+vA8A==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:U6Fs9GoefEwZROjEWq+3TI7Sp8DRuDbviw==,iv:lAEsNYNXC+Xyg5zgNJlyMP0xCRq9pgqRNoMA2s4OQPU=,tag:3cxgIHvXOTGzwfTGMS0d6A==,type:str]
    SECRET: ENC[AES256_GCM,data:EU977aC+m79YGbaYLDyHHg1/bmnF4IZO5w==,iv:sqCKCD5WwBJsoRe5OY0lbk9EHcaj6lvm0rTwEUDOBR8=,tag:AxrmjgS9vQ2j5u9b5xYtIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dzlpN3d0N2VZQ0tid3pj
            QUFJYXNiT2ZnL0RtNWprc21RbTk2bHh1Vmw4CitHQU9ER2FJM2R2cmVYSCtwTW8x
            OXJHR0ZTRGxxRHV0OVROV1hrNUJmT28KLS0tIEdSSlQweDhta0g2OUJkZm1PNmNI
            MXk2MzNWUHlvRjZ1SlZJOFBiV1BlbGsK2huCLMgGNxX76gJ4jwF6MzTDnNKy75zX
            ZG5qCz/VGBKq4TFm3T4kJNml8o+0BuRbGUpv8FmXO8LGlURgcpnSZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T14:08:24Z"
    mac: ENC[AES256_GCM,data:uLYzwIjaLV+0XM+0Q/9nTQNdWlBWqo3gG2dLKvilszo1FqMse23E8m+FKwuvZANuCJwmDGuw4XeE+umUpZUZxJ4li7/PAg5PadYwFpy1d520c9Ky4Q4vFgfOBFPNndP+LIZXAe4hpD/3d+Q9lOvYvvRXpzg5SGUAyH7CNCNLLuA=,iv:JYRxSdfvMCe7n9wGPrEBs+PmjIxCT13T2TqPNdz6r58=,tag:mKpx1IvWVL/7eFD45XqoSQ==,type:str]
    version: 3.13.1
