apiVersion: v1
kind: Secret
metadata:
    name: linkwarden
    namespace: linkwarden
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:GOmq/iVM+dUks3NtqJ6Bp6+Ci+37FizsNKL6q6dafXg7cd+frogTl9hACn5wX/O0Sz/18CuF5iERuBLbLqWqykQcxSTp89LqClJs8OT0un/1oGw3zUNnz7SfL3Hk,iv:pkjaAj4a20jG0dZZM6GQ2Zf73Z197yfc8tSWbX4xz6o=,tag:wlUEW1S4+dF87GtjWM/9nQ==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:HgLbWpmaU7kD0TVzti8PDlUvvAZnIlmOlQ==,iv:4+C4adZ/VUtqpgUgHvy+h0bV7VSd6chRwamUxqMZnN0=,tag:ybwshyLJNKzGqzCE7BoM0w==,type:str]
    SECRET: ENC[AES256_GCM,data:lAAKIG9j/6+i63QhSMLcwMoi8Hrd17z7Ow==,iv:2NW2iY/7OO5DJbMiYQrQte29raKxxpLhpzkseoRVdqE=,tag:RF1ngNem0GlZ0BSKK3Q6GA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWVZORG5JR0hNMGtKSUdH
            Qk4xRERrY0ZTQ2VNd0JCQTM5MVZUa2FNbFNrCjd6RUt3c2pWdjU5QkF6aXpLVi9Z
            QWdzT002TExMRlpHc2NabUFnNkNtY3MKLS0tIGJKQkRVa2xTUCs0NkVtdHB0SkZO
            Ni9wTC9lUGJQdVNDeWRzYlpOU0c5YWsKNa6PlXsZJ60btN/xNC244lof6xLkZyCs
            6+Fjv39E6KiMUukF4iVPnPbwVh50Kat1yoK4fftZK7CeOjNDPkzVmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-10T12:02:33Z"
    mac: ENC[AES256_GCM,data:r288rrIXjpa3Uwc23hm4d9KIRpbLNwROA7WoNKmR5aY3fXEsUt8QgWMus8H1DWHzLEeXUcB8duH6qxTlaRkgGBfzcNyqFUeCSQpuwkIRWLOqdtWLa0u6TXXnDboqXLSajhYLBisykzftYslfGKMBCO+Iz7Tslw9uxitSQRBUyEI=,iv:RJw0at55WMh54gdTb5B+Guzzf6AU0u4fzc/yr0a8cOM=,tag:yoKJ4pVz8E/pNtH6+Asj+Q==,type:str]
    version: 3.13.1
