apiVersion: v1
kind: Secret
metadata:
    name: miniflux
    namespace: miniflux
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:Ks9EbHCWETyyVpEZcQrgevRD6QO0qABcEwimFVFOPSO8IS6UHfXGHzoGvV1EMNhQpf1/oig8XQWDnbBSZpSlL6D595pgT95onWHxlGYemIIOkuNWj1WWQ2LlOEOFkt9cdRGs+OAGKfo=,iv:VQ7BGLSoPXrwu1+oa1MWTRT2RF0wxMnA52dSH/C6TfA=,tag:E/5K7xakGUJi6gvH4z4Q4A==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:FjsigFfaSQQfCGf3TVq0m9yWtoaI7PpF3ohqI+ObeOQt,iv:UeJ1+eBI3SYVGEka7ktzyei1el8KGX9AJux7BBTLqN4=,tag:m9YhZ0VPvo+jnQujEGrZSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpR0Y0R3l4MTVlVjVOb290
            UkczQWNxZUxWbTVPenYyWHJGLzk4ZlhHeDMwCjN4M25jTHFGL3dKbWxpT3V1VzdV
            VXYxdEI3aHN1ckYwM1MwY21WMGo0VW8KLS0tIHA4bVNyK2RFYWdyM3QvcWUrMVNT
            OFNveTFhTGZKTyt3Uy9wKzFLWURpd2cKAa1iXlB3P2b/H6W5CWrSCemwf6AOEK36
            NroBoCG0oSYe+rK3CamAyFXxQCKjFrw9xY2QXVbzw7n4HTquR11NiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T14:01:29Z"
    mac: ENC[AES256_GCM,data:mhC7ykY0bmp13DIiOD8b/YljNKHQqGJyWR7OQdbZmBm3v39jgiS+pl6TFS/tBGzZZj6s6Z0W7q7okMHTE6IXIloA5wcGgDXd63gd43VBuNKQEmv75L1jiyXEvl0Km0Q3U/p6+tklbrClONMAM2GA3ZbjyfCLmSU07uPR5lQDoeg=,iv:3yxBuAYBbs3f4fn67MVpJA0Q/QDbxkR5yt9JwH6+Y+A=,tag:YFF7qUpgjdByTWImp/ktGA==,type:str]
    version: 3.13.1
