apiVersion: v1
kind: Secret
metadata:
    name: speedtest-tracker
    namespace: speedtest-tracker
stringData:
    APP_KEY: ENC[AES256_GCM,data:UANTENV/QU4qP4M0dgOmRwZxBDYVnBwDhhhxx6tTGr2y+0ZEI0xhOFYBRsE25mp85lU7,iv:b/yFk9o1beDSkhVjoHgDfiluLka7VjXJNkywD2o2Nbs=,tag:Jz0vXU6SWZR2P0NbpBB/fA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEczBUemNPenNNeVM0UC9O
            QnMvSnlXdXhxMUpHMnNjMzl5dUxqTGhkbW0wCkhvTk9yekh0bEdsL2Q3cFlUdzNo
            OVlIcFhYZTZ3dzVvejdaWFBXZkl2QzAKLS0tIEZhK0ZqTWhNQWFqU01NSWs4bjhB
            UUNhbFREb1pySzVJNHF1KzNZOE4vT0EKm8oZO1G4/mnVbmA0i4hFMm2JZJttHgu0
            AnkjW58I/WZCol5NhARmoBRIwGYwWkvbOxN//6D3iWwhitAPMq4Grw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T07:40:57Z"
    mac: ENC[AES256_GCM,data:6tQzrDoVFHEC9eHjUUEtE0m69AFB767Zodmtu1OXsYPdPIKosnfxkXODC36Q9nD1e+WStuvbgRskP/ErAP/LJyEZwN0PC6/H2fXfkEOMEgi+wdSylkfcvqBCRQ+Jav0dLfxiDubiZEjapUDLILf0ySpsYFr6cb5s0RCh/GKHJHs=,iv:+5c/oh2fPVkFzguhEXU5KEFHRcQeH2fazTJbv+BO04w=,tag:4kY8Ghj/tflygdM0X2uvyA==,type:str]
    version: 3.13.1
