apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrelease.yaml
  - ingressroute.yaml
  - ntfy-alertmanager.yaml
  - ntfy-alertmanager.sops.yaml
  - healthchecks.sops.yaml
