{{- if .Values.networkPolicy.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homelab-app.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "homelab-app.selectorLabels" . | nindent 6 }}
  {{- if or .Values.hostname .Values.networkPolicy.ingress }}
  ingress:
    {{- if .Values.hostname }}
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "{{ .Values.port }}"
              protocol: TCP
    {{- end }}
    {{- if .Values.networkPolicy.ingress }}
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- end }}
{{- end }}
