apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-releases
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/infrastructure/releases
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-namespaces
    - name: infrastructure-sources
    - name: infrastructure-secrets
