apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/
  - infrastructure-namespaces.yaml
  - infrastructure-sources.yaml
  - infrastructure-secrets.yaml
  - infrastructure-releases.yaml
  - infrastructure-configs.yaml
  - app-headlamp.yaml
  - apps.yaml
