apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kafkanodepool.yaml
  - kafka-cluster.yaml
  - kafkatopics.yaml
  - kafka-ui.yaml
  - ingressroute.yaml
  - networkpolicy.yaml
