apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux-controllers
  namespace: flux-system
  labels:
    release: prometheus
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - kustomize-controller
          - helm-controller
  podMetricsEndpoints:
    - port: http-prom
      honorLabels: true
