apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterissuer.yaml
  - wildcard-cert.yaml
  - tlsstore.yaml
  - traefik.yaml
  - oidc-auth.yaml
  - traefik-dashboard.yaml
  - hubble-ui.yaml
  - proxmox.yaml
  - intel-gpu-plugin.yaml
  - flux-alerts.yaml
  - crowdsec-bouncer.yaml
