apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    priorityClassName: system-cluster-critical
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
    logs:
      access:
        enabled: true
        format: json
    experimental:
      plugins:
        traefik-oidc-auth:
          moduleName: github.com/sevensolutions/traefik-oidc-auth
          version: v0.12.0
        crowdsec-bouncer:
          moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
          version: v1.4.5
    additionalArguments:
      - "--entrypoints.websecure.http.middlewares=kube-system-crowdsec-bouncer@kubernetescrd,kube-system-nice-404@kubernetescrd,kube-system-maintenance-page-errors@kubernetescrd"
    deployment:
      additionalVolumes:
        - name: plugins
          hostPath:
            path: /var/lib/traefik-plugins
            type: DirectoryOrCreate
      initContainers:
        - name: wait-for-dns
          image: busybox:1.38@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
          command:
            - sh
            - -c
            - until nslookup kubernetes.default.svc.cluster.local; do echo waiting for cluster DNS; sleep 2; done
        - name: plugins-permissions
          image: busybox:1.38@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
          command:
            - sh
            - -c
            - chown -R 65532:65532 /plugins-storage
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
          volumeMounts:
            - name: plugins
              mountPath: /plugins-storage
    additionalVolumeMounts:
      - name: plugins
        mountPath: /plugins-storage
