apiVersion: v1
kind: Secret
metadata:
    name: atuin
    namespace: atuin
stringData:
    ATUIN_DB_URI: ENC[AES256_GCM,data:43PR5LlxLiIfsPN58IduvsiHZRELip/hJAtFwK+/58tb0wf21yUtKn1uF0wGbFlTxwx0aFVm5MQd+aiDRw==,iv:WP+uqn1EEm5hzuuTNg3eeE2eYXRu20zMzA1pLgkgNIg=,tag:q2eFKNqN+MZTbHLH9gsHLg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TlhuVjJDWFM4S3ZCYkMz
            OTM0M0l4M2FUdnMxQW5JLzl2Q0xSbHp6SnlnCmV2cnZhWEhudWNmSnNSKytEN0Vw
            WUhHZG03d1JhL05FV3pDbGR1US9ESXMKLS0tIFdRRDVLc0s3aXQ4aTZHWitmeVlI
            eUhkYlVqa0RLTTVDR0dVYnljdTl1dlkKDi7PKEnEiI4xOPjjjJEdZNjs9eXdMJV4
            6I4Zf3WCeHh2lIGmgnGUiaUGwnH9TUIj1OyWpzr6sdD4VSEl5n3YUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T13:26:30Z"
    mac: ENC[AES256_GCM,data:kORfOdjij45odRVy0yzy3Yd/zeXlyb5dsI6URErSfVhouD8ShV0IR+oAB5k7MgZqtKHSAydBMLHnVX/IIDrjjVqXuYSqzfIbWDlXk9yYyN1l/qSrhVYvdkRRCMZQxE6PQ8uX2qrV7flAvXkMzpWQvNaN8LkAu8LRFIr0sQqsH+g=,iv:KPcHf32NKys1Eprl6elERW8EU1LJDTQAAbIslzxDhTs=,tag:DWlzBxIkB/KhD67bYg9Tdw==,type:str]
    version: 3.13.1
