apiVersion: ENC[AES256_GCM,data:hC4=,iv:jTAK+I29sJ8wn5q5IcBH37O5a6pwC9WbvRr3pfk7riE=,tag:Zu+IUkLgjymEUZcs9kgSzg==,type:str]
kind: ENC[AES256_GCM,data:S1tYKTyw,iv:WAlRGMR2t5fAlDFhZvw1sMknZO67ya81m0smsc1qxpI=,tag:YucEtqWtIDX35NypjSO/Ug==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1YnPtyhH76TTq4eVzXH2lV9sTZc=,iv:kNDH0/jJmlIzcGLUNmd02Z6fgKKzG7GXglDOVYQzvMs=,tag:hqh7nDtydr+CrGeELdrfMw==,type:str]
    namespace: ENC[AES256_GCM,data:2xikanXgUykOrVEZ,iv:9LAqM8DfFpSXmjAUGD6o9aGnWt0DkcFSnGZ2NUqx7pA=,tag:W+P+Ns9xZQHutjG2Kf/ZYA==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:S12el5eTK7lCq41HrsH2PxmLcEteBlmhnpQvFZcIVGNGMsQZUi2xGg==,iv:1fpL8AiovBFfjZZfuC7t1lnmfcHpcejjBOC1zERkNI4=,tag:CfDJH8YWDAKunlKX8KstHQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByV2E2TkROUXp3MG1IUGsw
            aVY3cndQM0t2VGFmM1pnY202V25iM0JTRzA0CkxEVDAyL2VybGdSaTF1NXVYMXFD
            aTI2alBReWZxZHBubHlaK1RDL3lMUUUKLS0tIFhKWUlKckx4QXdSN0VSQmNoTm84
            aHpTbWpKZk5wNFp5QzIwdWdYZkFtYXMK3omz6U1p8MU80ugMGle90HiwKb/Sz0A+
            riwRi55qwP3+rhfYePUcgA4oay8LSmjOP4bZ1Z4C2ejpg7PrP/XEqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    lastmodified: "2026-05-24T19:28:39Z"
    mac: ENC[AES256_GCM,data:xE7DVShIXLWAJPlinxSjwugwEQg7728tDEqQIZG5wg+z1Q9Qen4QlbuaImNtIWTW7MyWZbGdMhHUoNZIroqsiRWNiAncPgJFehhO/jPV7HNReVlQRPi5UQtQR90goM4te+VEgmgMSfw/Slyscp88d0sDSWtnvojOGRIL/1tXZR0=,iv:zVJf9YBYpLqyrvQse7nbUV/eGOaCoTzgV56plPZkY38=,tag:jxY1Y5Fky0SMSHjyYbRIbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
