apiVersion: ENC[AES256_GCM,data:mWI=,iv:a5tghj5erScbZHjG2PKj06qOzTGlZMH5V8CxMTYaF8U=,tag:X1ZtcOjfYNEw5HdYVCuBaw==,type:str]
kind: ENC[AES256_GCM,data:UIZoZoqN,iv:zgF+Dw5JiN25Ftj6lzP3LvPYZy/0RKYS+NNbV95dN2o=,tag:CfS9aFRf8K3oDFRxtQDnfw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NMmbtWmZsZTFkcpG4awkKIhTREe2,iv:KZqtym0LLz2bqAc4JWtlg/hUlhuKh+M8pHA2ItiPPLE=,tag:w3FZLAiMvpSBrVMgkrT0Gg==,type:str]
    namespace: ENC[AES256_GCM,data:p9qZ8B8iW2usSTmPqrc=,iv:lzDTTllzgFz6lekhBZVJaU53ztS90c2fTFSRA/Tt01s=,tag:qJyEa/bPVH3S9fqoiqcVkQ==,type:str]
stringData:
    values.yaml: ENC[AES256_GCM,data:HMLAucpYgTEqdCJ3BdFKtx6fXuCCyGjvp7JqtmuHbsON7HIrOae4PqtuZpg3jsUAyoJrt/uYEWZJYFmoqnMwGS3yJ07FLnJTplwCk2fYhx6UbijdbI5euCxWm9dOSLw9cgkvFdIFAba4LxZ8E7pLIxFIXRMeEcmcuWUtUwODJnaiebdoNoseuzJNE8ZzBXzyvXXP4xMwdGf9J2k1OVTMHszYkbRnqxL9E4oviOAReCWHWq9hce7N0ZfDd6PYxY/GhiMadfj28dzWlXPEV4DM+kxJ5Ec75OrCeh6sUb20fGXPV3N72f107r5YeH3jNYjd+WVEllP8N1AfkOHXz2kWU63ELV2UdaZuWQoDKtOH4AE9zfihcUymhqVzzvC2JMVh+f8Yv70kvqlljw73yv+/cqcxOpk=,iv:ZL4OzOuNvqpSLmBR4M0Vfu9XLu2UknREY2ekfZkgdq0=,tag:y2xM7TMd3hAnZfTnIOsGJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdkhobkovT2E0WGl4dnFC
            ZTk2QTQwaXNJVUtTdzIvc0NVN280QmY0YURjClM1L2NzRVJRZ3UyOUFaZGRXQTI1
            eTV6MzNVYXNYalQ1S1BOVmFSb043a3MKLS0tIFk3VzJsYm1VZjAwRWt1SDEvMEpI
            eUUyaDk4aFB2OHphblNMZTA2ZW1aN0UKmKrIgCckODR1QGb8amhVDxiQpGMHxB9n
            yqaDTbfkrtGJ0Xykx4b7Gpywze1WqfW4QmyRA0rnclR2zA61F+MgEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    lastmodified: "2026-05-24T19:34:11Z"
    mac: ENC[AES256_GCM,data:JvqwcFrUS/Hk5yElL98SRnXqDY4n3t4Jaskcg2TccOuQKvXKBM2MoCgAZ6ofxMYJV6nc12b7xpmLwdWjCZD3KHGDHtEfnsCfBzkEnpp6ppIzOhyPrX4Kgtq4Wkcsl7rJAj/a3wkSoBVwYWtbp2Loz0mwqfs6HVn8v4cFtqCK/fI=,iv:ponwNR17VcCAFJhvcNQq+XIIyqu7VrJXI9dn675Z10w=,tag:D99QVA9jJ+gy4TXVp6kM3g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
