apiVersion: ENC[AES256_GCM,data:S+o=,iv:myl9y12vymn81x72/WQNA1PKYJRkEOTiYrZoywKCp9c=,tag:Lr+GcimAn+w3TkLgkW6n2w==,type:str]
kind: ENC[AES256_GCM,data:Zh14JC3C,iv:akb10X9u8akV62H13ZRsctLJyiP7IvdajUHh0jj4Uw4=,tag:32QkjHZpwxccDOJKGtibEA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1M5McxMw+WHiWoikCBxOTmDLfw==,iv:0i7drCvN+vJIViBxvt6i5I8wL/Jqr+6GKCBOu2zMfI0=,tag:89rbWFXGa+J2o2MAjphTrw==,type:str]
    namespace: ENC[AES256_GCM,data:WqcmIoGrhlQr2Xo=,iv:3ytTiuqpAt+C2YolqksdcdSqVjlq/gmDNfJjI7aq0As=,tag:mBjZmY7WkoYyQrQjJXwdIQ==,type:str]
stringData:
    token: ENC[AES256_GCM,data:Pd0O2eketJhOrbzILYB3I3EhPjL6VSPr2qI0T6i4b+qys4/dUVjhfQ==,iv:5OLcuv2FSfiiY9vn6IIafCPJB8VMF9D5QRbh8jEqUOI=,tag:0+aMyN4hVVepUP4cMZbSwQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvM1VtSzMzMGlzSjFOaDZV
            QWkwekJwTzBTUnhvQ2p1Ukd0LzdGOVpOUTJjCnlaZkNpa29PZ3RBd2ZubGkycTBW
            Ymdkc2d6ZXdUaXdnNHJ4enlLQVJFUDAKLS0tIDQrS1JubGVHU094QlZ4aDlqN1dy
            WmxMdlhCcWI2UmpRWm1vemptald0YjgKNwEHMOLgxWXIQ13pivGfoCCdmkQ7aPct
            /0qBPtcGGMc4iOY8nZLowbEP1smbMHkwPSg3dH2A3OmUv++VIIYhuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    lastmodified: "2026-05-26T08:35:11Z"
    mac: ENC[AES256_GCM,data:nHu1U+EY08REFncmrVJ4BcHd2cjjltS7u+AX6sjia8X1k+VxIYBAkpcxLxxg+0dkCSxY7dreUkZ1/DBRANuxc0K1J5vJBLa/wtQfwNtcZ1kiilN5RHaClLBy0OBGQ3s1cOozvyE0Q7i1IMoqcm7ivVEch69vQhISrRWodTONKbA=,iv:ELIxsiTroYoOfPenfti4VQHt6lRL4xXt+yn3WMq07lA=,tag:FRwt5MrJpHRmQdwbUWBOXg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
