apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare.sops.yaml
  - democratic-csi.sops.yaml
  - gitea-deploy-key.sops.yaml
  - flux-receiver-token.sops.yaml
  - linkwarden-namespace.yaml
  - linkwarden.sops.yaml
  - atuin-namespace.yaml
  - atuin.sops.yaml
