apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare.sops.yaml
  - democratic-csi.sops.yaml
  - metering.sops.yaml
  - gitea-deploy-key.sops.yaml
  - flux-receiver-token.sops.yaml
  - homepage.sops.yaml
