apiVersion: v1
kind: Secret
metadata:
    name: linkwarden
    namespace: linkwarden
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:wOsmMZF0z7UwkqQMhAl6XgmxrMtmCkAKZVsA2LFmZh8+lP+a+LYg5nVEpPBrvx5S+uv/Ec0SGor+KJW7CYRQsSqL6XsqelVQabWfmJkLdxq+NEkUlw==,iv:UcWHUg4zlwQ/2Rm+Kzqa47ET32De7ZlaK/6gu43nyMw=,tag:6D3H12wDBN+bfMSX0QglqQ==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:ArtiBIWxdWuDhIXp+WSp3VbF8bGMSmNTkw==,iv:JBCDQZF9fqTAW7YLeHlMMZan7ZPPhGrlpm+ZOVkZdBE=,tag:I3nzFqqtp9mNvidn8+tt3Q==,type:str]
    SECRET: ENC[AES256_GCM,data:gD2FDE/5YCqdNuWcaUYllPEsv/nST5xTlw==,iv:djhfFLtWhDkC84j3OFYIPPZ3D5gIlVRxgf5LQh/Gr+k=,tag:aID2SGfku+jMgbwNtSLuAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxM0M3Q0NidXA2WEJjZFNt
            cGprN2lTTndJdk9rZ2RndjluRFhGZTBsQ1dnCnpnQ1hESE1iV0wrUyt3V09KQ1Ar
            S01LY3FvM3l6Q3o0elV2MXZWdmZsY1UKLS0tIGF0WWliQW03L3MxZGhFWXduRDh3
            NjMvdHpkUVR6TS9JYmVtWVZWNlgyaFUKnbh/+cUKrW2llkv1we6Wxj/hiJlzRoHf
            hwkJoGF2GR2+KBiah9YUQTcaibkimyYWGid5q6yMi05dfhBMcvZ3FA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T10:25:20Z"
    mac: ENC[AES256_GCM,data:3/CebgMnpI7fTp63VbBm8NpuHpo5/zepnjjZImKRSUSS9xvvFfyUdxnXKTr5nVJCYF9bV+Y4pQ5l7Rioi7kyR1gqG3eJYMcmQEVeYIRXEcWXjMxkDjTBn7zIoFP3MpaQ5tWs26WvJO00EQYNZYmeaSb2K8VozOEbb8a1n4eDznU=,iv:iTylrg6Iac4PcI7dtoBtHcwpz8CwQ7DOCaL0HEN6K3o=,tag:fWQTUGJOA0fVuCb7YbzevQ==,type:str]
    version: 3.13.1
