apiVersion: ENC[AES256_GCM,data:exA=,iv:EsJ3x4Hs8iBQlV5CxJwc9SuPCyg/58iEBmkLaD0FnOw=,tag:b/9az+S4FoJCYAkMr2hZmw==,type:str]
kind: ENC[AES256_GCM,data:dCGkcDvt,iv:zrVwl0dkd4nuKDnnGgL9ipQIUddpJG4SWWTaaOM7mRw=,tag:hqG3ODwldCAHjjRtpJ4MoA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:B0F2ofns1cK+AgaXeMpfVQ==,iv:zf/Gv0Msp5YDGG2WQYhbnMUVPEgL7/n9QytvviB641A=,tag:+0EWE1XB0556z7UWvCi/Nw==,type:str]
    namespace: ENC[AES256_GCM,data:BVDEKEbUerA=,iv:EIisNDw3NcjOFqZHzmaMEXD7HRNO7IixF127TEuGs5o=,tag:NgUpNsyIzRhLOPSO8N0OFQ==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:tW67qZu/H8SLX4pvajaoPUn2bir9LCCi2NFx,iv:AWtR2Rx6e2dfZvfMCuqgREGoSr3UFPVCJAFEIRNJeLk=,tag:JAvXUDnwzCm/cVphPqANBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUjR1SDMvYklLdUJSdGNH
            Sk9XUUw5MFc0VE0yU2xJOEtiajZmUURDLzFFCmN6VVU4WjVxQytGMnY1aGVuS3g3
            YWRGNFZrRHRxanltZm0zcWVlMlB4UVUKLS0tIE16cWFMaUUrREVETDQwbU0zaGU4
            WUJwdlNiUUdaYnliQXJPRVdkV3U3SlEKuecuYZIbjmEeyVNOhW1aBDA0Cph/WHRi
            IF6N0hy5scOr6RAnFPZqRjlk5Swy6mDm7TNkIRVlCv26ipPq8rll5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    lastmodified: "2026-05-25T20:45:03Z"
    mac: ENC[AES256_GCM,data:eTc1tmfA8+c83HTrNj9ppjW3v8+xGHyyhYhsyhOGjdfyoIz3w0POXzVzSQTO1GpU5RCaoyDmmyMJbbPsM+fo/uedVyp0UtLUWjCT8uqGto5uO+qwc40eOfKHEoJpQcOwA6rP9qIC0FjNTgFdk3/uapO3EI7rCcjETY29gPkfkQw=,iv:Olj9Abv5/QWIll6WqVcZQ0iueVs6PuTLP3SDnDdfWb0=,tag:CJXAGNWIbMqdqww61H0HCA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
