apiVersion: v1
kind: Secret
metadata:
    name: miniflux
    namespace: miniflux
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:WPmvpKcUyHvzN8d8rmqDcBe8Kyvzwp6KetoN45iqV+wux75K/W5a6A50kQu8eKh9FJZKiTX+P2x5BSYRiXVmeg9M8CnIE9/spUEKwxylMToox6pcoZWy9S6Se7rNvDFP19E=,iv:f1XBI9xNCEzaeq06fTP0mti1nqlR1aNrP5xCZjI/PhE=,tag:KqL1htsbhJL4R9GPcvBY/g==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:+0ZRcz723yuiiV7W/z41cMkcv5eMlBCHbgBgbqy6KeeJ,iv:Mz0kDC5KAZrgKgO5+42FTfQe5BAbHwff+tUId8iQWsQ=,tag:U0rb/5j0A1Vrl7kJFmxy0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTWtIMEhMVkFNMVVVeENU
            Yml0TWZUV0FtSWZSU3ptYnRLRzRGMEZzU1dFCjMwSDNZWmgyRGtQUENQRjBUaE5i
            UmIySSt6RVVzR0hRQTJyTUNCWm5PcmcKLS0tIDRGTit3SkRkTFYxakprV0tFWDFD
            amF0Tnk2TFQ0M2R6Mk44b21La1h4QmMKj+zGCi+Io2K7y8BXGbqlddc9Zfd448jI
            xDgvgiKdQI6KqpWBkWWGV+k9UOu8Y0dJ69QwHzB+drjdgllEwJVwEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T10:04:18Z"
    mac: ENC[AES256_GCM,data:6wbUig4a2uTWCX8FiIDQU30xZsob60VbYfnTQHm+Rcmp7x0JbfzwHRhqBL5R+2VGS/UYAuun8z/RsEr1yTaFWK91JZO7eT+gb9shMv5gcqW4dHHuCKpE2RpLUGzN7Ttdi4hiYuUCLzTmdHIeXVk5bDWr6f3bh0soh3JsW39b+fs=,iv:FbTReI+ktHTc8VVxVA462gdxMsvso4PqFR46EqIlfyk=,tag:3hQKVLoEykGW5t+gjZK+RQ==,type:str]
    version: 3.13.1
