apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secrets
    namespace: pocket-id
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:7EAmzrXVmTyjqvcEZhYqaqUvo81Qpc0/wmPEhhbDJB1SGC1DhTI02RqxTCE=,iv:2PbRT3uQxMwF+sfoCCne594MpwgVCFSgZiefRf4CTNY=,tag:HVuRfIL8dKnt2NUDAg59fA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Z2FQR01sdHZra2E3UHp3
            eVRnSmFxOXpFQUpHNTY0MnYzUjdzYUFXbmpRCnJsazVqMmRhOThTV3NzNUhJNkhk
            TFlIWVF1UHJHTDIvcG80dy9MOGhCT0EKLS0tIGJrM1I5NjlzU0pqN056dDg3MFVj
            NklQZFFDek5wRUo1eWxTR0tDN2VPU0EKqwL5uAjNWtc2nv9Lw1fljjdVhkSwj5Lr
            n5M4E34qZe1F86tGklwuctn2uR5lTu68xBnCS9LQPaFCSkOJFdP2yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T14:38:43Z"
    mac: ENC[AES256_GCM,data:dHvjzzAFmURsDgIUeYzRjH8xKddIrG1Bjtm3pdZjO59fojxoo91M1osfbepx0zsvrlxm4a6991mv1WvhiUYbuARm5AvzmOfyvR4TJ/p56jamA6TO9bLsFg1xOcGkQ6Zpd2cW4riiP4FqfFUX0KrCHY9z3LMel2LjOkBlg6Nza6U=,iv:eKwT2Ko6Qw3hww7jQgyr8rNLTcf/JNy24aGufkumUbk=,tag:p/Vyh3W0eINB5orZKcTi+A==,type:str]
    version: 3.13.1
