apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atuin
  namespace: flux-system
spec:
  releaseName: atuin
  targetNamespace: atuin
  values:
    image: ghcr.io/atuinsh/atuin:18.19.0@sha256:4d0ccca1d151f860b3f469c60df78bf1ab798f15e88dc1912d31d6741653eb99
    port: 8888
    hostname: atuin.greedo.net
    args:
      - start
    env:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_PORT: "8888"
      ATUIN_OPEN_REGISTRATION: "false"
      TZ: "Africa/Johannesburg"
    resources:
      requests:
        memory: 8Mi
      limits:
        memory: 64Mi
    readinessProbe:
      tcpSocket:
        port: 8888
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 6
    livenessProbe:
      tcpSocket:
        port: 8888
      initialDelaySeconds: 15
      periodSeconds: 30
      failureThreshold: 3
    middlewares: []
    existingSecret: atuin
    persistence:
      enabled: true
      mountPath: /config
      storageClass: nfs-shared
      accessMode: ReadWriteMany
    securityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 3013
      runAsGroup: 3013
