apiVersion: v1
kind: Secret
metadata:
    name: homelable
    namespace: homelable
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:64z+ssR2f3fN7uG/zDFUD2DZx2CvR013CgO49TMc8hHPMo8dHoQg4X8XU5NgjFtFJaG0/NKYvWqgbp1TnrgghA==,iv:E9RSFQaYN56nUplYVP8pCwJN2d14BpqRK/qWr4RJBWs=,tag:Yp3I0mtxln2SMGUQKH5y3A==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:94y4EUOovR9mH61jxDO4AI/9e5NTCzBAL69/L1jGNTg=,iv:JS7Gru07B6s5JWBuJJ3mcKD1EpPaI0Dj7TOOwDhEW0s=,tag:4WN4FFBpVF7+MHnNulrQ2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBid1FmSWdKbDdKeFNzeUZ4
            UlhzTmtJMnQ5aTV4aU9hN3BnR2Q2QmljUkFrCjBBMTZEckVrVXJXYW1acS9Fazlj
            SXl2ZldtOFRuaE13b0tkNjVEeVJKRU0KLS0tIFFTUGp3aVQxVkpZdVBmL1ExOENO
            dDVGd1VUQWRSNGZVQUEzUmVkV1MxekEKWsdNEQZjEf3qiWeETNN0cWv5o9uNWvy8
            0Kz4epBdegiZK+4JCxCePmLOq1mxL6OX6XrUf3j2BeXhqKb5m9YBDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T08:23:23Z"
    mac: ENC[AES256_GCM,data:YqRoF6GymHzs0q/lbMsoYvn33yJkUz8sfPmgm4hi85YvMVaFaGGm2lPu347Pf2dDvenrulPVfjkiGKTyaH74xjmsGdcEi/yTECiFWaBkerAlBXry4/Y7yCi0FpXp/vFuB6NtyFF14JJMFlxWm/gomG06PzjUOEAvWoF1IAYAt/A=,iv:JJHDhgYQJSXeTD+wGtH8m+LElyZQXH55pTJ+OIuK+ko=,tag:AFOXNmkGJidiiUCStIItVg==,type:str]
    version: 3.13.3
