apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backrest-scale-downloads
  namespace: downloads
rules:
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backrest-scale-downloads
  namespace: downloads
subjects:
  - kind: ServiceAccount
    name: default
    namespace: backrest
roleRef:
  kind: Role
  name: backrest-scale-downloads
  apiGroup: rbac.authorization.k8s.io
