apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.sops.yaml
  - slskd-secret.sops.yaml
  - pvcs.yaml
  - deployment.yaml
  - services.yaml
  - ingressroutes.yaml
  - networkpolicy.yaml
