apiVersion: v1
kind: Secret
metadata:
    name: downloads-vpn
    namespace: downloads
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:iLZJooNpnz9BIksPqdl6ZyBTB6V0ssPfjjfY4tKUSBqBwczvxu9+1JeNhu4=,iv:lS2mJaNQ3GarEGc3i5w0UC/TARdvyMC6QlCDdDfdwrk=,tag:NM15ijbRTKToUQ9Xm5i7Xg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcGtibzBkdG43K2lQY3ds
            UWxZZFJZRnB4WkNnYjhwY0VUbFZnMnpWNERBCkllTUkrM2xWUWczOTdUSTFwMTFy
            NzFsdDJ5eDFlWG1OQXlNMWV5WDRVbW8KLS0tIHJhb1ZVU3I1Sk5DM2Y4eTFGSXZF
            YWY0a01tcDBWemMzTFExNjFnWWIwTE0KOfdgkGGi7bRPJO2nOsC69AsOMkEpAa2L
            Fsknnd79/0bELDZ8jvh4LePTEc5DQDeeZ+rRF4WJjVJmk158eCh1/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T08:15:08Z"
    mac: ENC[AES256_GCM,data:5YbnF0j8049GGmHcnrxwqM3iolDOF6lC96CNN+48UT1dITzbT1mbfgxIawUSKc4vNpDUNLDKT9nW0d6EQOwJx3aL2PQTfpboAIp59FUzBTYA44xP7MWuqOtgJumT3FySe60dLLTE4xog6UdNTUV0/u5I3Px8FKhp5yEI3eVcZfE=,iv:DL1lgUz1LmWC1qh09emIJZasY5h7QhepQslEFqtDSv4=,tag:tuZbNhGJol3nxbrMsm8t4w==,type:str]
    version: 3.13.1
