apiVersion: v1
kind: Secret
metadata:
    name: slskd-credentials
    namespace: downloads
stringData:
    SLSKD_SLSK_USERNAME: ENC[AES256_GCM,data:VAXJbSFogEaoMyoILtPpECSKhSD7pA==,iv:5ji1vLsx5XIW1ZxBNW2azylEz8sOQ+pxrQZuDJ898KA=,tag:NFVli4QNAkFuPiA8RS7Dew==,type:str]
    SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:P1QQZ5/KsWtGPml09Qm0h+lldTeT/ba4E06q2FA2,iv:Ll+s2UU/OPpxWiZ6DM68E8KkUw8EtnzVgsgzMzjcWLg=,tag:j3RwBMNBNXytiGtY48IVew==,type:str]
    SLSKD_WEB_AUTHENTICATION_PASSWORD: ENC[AES256_GCM,data:OBMZRANhQtM3P0iSAVNadFQ31D42MVJhdK/4vucB,iv:DijoboUsbb+O5+MjF9patosANm2KliSJGl+uvqOvde8=,tag:bKSMEnLo7rttBtt1hqgcsQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUk5zMjlsSlROdGhNNVFG
            RlJPLzkvVnJyaVl2N0w3VjN0Sjlhb05kV1FzCk9kOUw2Ump4MWEzVHE5ZVRVaWEv
            YUdUMm1aeVlpcXlFbCtrb25venluelkKLS0tIFZtQWZwTEFXME4waE1TNDltVWhu
            L3AyL3UrKzBoSm5QaE44ZEN5alZWdmMKJi2omSn/+tRVyKt2VrUMyDIL7EBbUgc5
            H8DdDjoOlt3guPQKG3OnKlU8EIdB8o6kcy8MMfF8BUgrhkYYdWW3mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T08:15:23Z"
    mac: ENC[AES256_GCM,data:7QUboMreyKyvvcIZcgy2IkJwewsNNxoSikmkGSDOXcl+kAzHrvHnnrxkDzxtvPgcM+Ba2UOI6Wpsm2OFt24/GvfCJxu+skuw/0xTp63OXyRPIzgCWyoS40OdfaUkA8xorErtk+qNCaQzZdA9RHlM/QDVDVeHBWURLUqfN1bpTvU=,iv:6tL4Ynb7e8fUjFZKYVkC03NYP9Kd2o8mQmL5mMWaOu4=,tag:9IFdTdVil0nxFdseWtVKyA==,type:str]
    version: 3.13.1
