apiVersion: v1
kind: Secret
metadata:
    name: slskd-credentials
    namespace: downloads
stringData:
    SLSKD_SLSK_USERNAME: ENC[AES256_GCM,data:VAXJbSFogEaoMyoILtPpECSKhSD7pA==,iv:5ji1vLsx5XIW1ZxBNW2azylEz8sOQ+pxrQZuDJ898KA=,tag:NFVli4QNAkFuPiA8RS7Dew==,type:str]
    SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:P1QQZ5/KsWtGPml09Qm0h+lldTeT/ba4E06q2FA2,iv:Ll+s2UU/OPpxWiZ6DM68E8KkUw8EtnzVgsgzMzjcWLg=,tag:j3RwBMNBNXytiGtY48IVew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUk5zMjlsSlROdGhNNVFG
            RlJPLzkvVnJyaVl2N0w3VjN0Sjlhb05kV1FzCk9kOUw2Ump4MWEzVHE5ZVRVaWEv
            YUdUMm1aeVlpcXlFbCtrb25venluelkKLS0tIFZtQWZwTEFXME4waE1TNDltVWhu
            L3AyL3UrKzBoSm5QaE44ZEN5alZWdmMKJi2omSn/+tRVyKt2VrUMyDIL7EBbUgc5
            H8DdDjoOlt3guPQKG3OnKlU8EIdB8o6kcy8MMfF8BUgrhkYYdWW3mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T08:23:00Z"
    mac: ENC[AES256_GCM,data:vBJTsHdGYmWwIsqcYP3oif/+vz9E/SujYNrMUv9495bfKi7BAxoyPFX7woQ//vVXyw7sCJ0ZPdMdrQmEevC2v2UpzqxpVBFcy96qxvUV284swnyg1PJHjk5j3+dTAFAbNx5RMX9LUUdFEqUJMZ9muFirG9l94sNyfV3WtdoJWdA=,iv:2d46W0gc0YQWdlmsympU+EmiIq/btSbpVhHscjn6oHw=,tag:CmRPcjuIdGvX+dtIlKUPSg==,type:str]
    version: 3.13.1
