apiVersion: v1
kind: Secret
metadata:
    name: slskd-credentials
    namespace: downloads
stringData:
    SLSKD_SLSK_USERNAME: ENC[AES256_GCM,data:SdaW1wgjRcKDtNW5VTv6OMbeY+U8jA==,iv:7Re1azOptsT4dWr7zJTqN9oqZINLYXnEjpa5g1vxNEw=,tag:cBLyBrNs0n19JfF3dL56mg==,type:str]
    SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:mT8yEwAx2P2W1qeB08AtD5cbhfmfhbXsNgxZVyoa,iv:NsS2MlfZ/7ltzxWd80WyallYl1Tp+A/qzrEqE9/pj4w=,tag:ns9a0+n1+5BPJLlf7IR6Eg==,type:str]
    SLSKD_HTTP_AUTHENTICATION_PASSWORD: ENC[AES256_GCM,data:MF8MEDQFW+riPxFFxLosXT8d32Wh5bNB/A/pO6Z1,iv:yb+ziUa7jq/yqbfczXiHi5CW/Se+VrcNU30g6VoVbwc=,tag:F/Q22o8oZEZNUPMKD4wEyQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHenpNVjVNYnRuT0JUenlT
            dGJNYjViOTFVVzR4Z0N2dVNaOTZKWGJSM21zCno1WnFFVFBuNjk3TC8xS0trM2pu
            WkM0cjBLdGJzdU5DM3JCdTJVeUw3NVkKLS0tIFFFakJjTkFpN1B6ZWFzV3hqSWVF
            QUdpK1VNZjB2OVNkcjlvOHE3T1ZzdkkKHPM64+BzmSA1X1eX63zwyHVACh/sb4BB
            5G1OYI+4w4+SSneo3PKqg62Ew1ROjrswnISxPuxjtAiSYhC7R4IacQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T07:50:09Z"
    mac: ENC[AES256_GCM,data:KkQHherkunNCDKXP9sKRcQpkv7gNigLWEDH9W4Dq5GF3KyO0901YxSWBYkbp88lNXYaLEq4NCg9g68ZYqOITFs654T5rt4bbTUtoZWDqBoeIQJeSjUMyPDD5w3XAQEggifjgMnOxNOEEe9M2kEsZ1qkRNXJLGn37endCA7f9mxA=,iv:Gn5xaelI30DPc3PsDUh86lDYtJ4fwBcNftKbuYGywQA=,tag:NPVrSH8IbZl8UiTWuJbW5Q==,type:str]
    version: 3.13.1
