apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whoami
  namespace: flux-system
spec:
  releaseName: whoami
  targetNamespace: whoami
  values:
    image: traefik/whoami:v1.12.0@sha256:80f8bb74f634d45d55967820a702c5fddf01cf92968bb29ed7a3573dd16b0e55
    port: 8080
    hostname: whoami.greedo.net
    middlewares:
      - name: infra-admin-oidc-auth
        namespace: kube-system
    resources:
      requests:
        memory: 8Mi
      limits:
        memory: 32Mi
    env:
      WHOAMI_PORT_NUMBER: "8080"
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 30
      failureThreshold: 3
    securityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
