apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: postgresql
spec:
  instances: 1
  enableSuperuserAccess: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi
  storage:
    size: 2Gi
    storageClass: local-path
