apiVersion: v1
kind: Secret
metadata:
    name: postgresql
    namespace: postgresql
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:KY3asYMJNdFL6DdXNnDcaDhMb2ioklxhpw==,iv:H+jx8uu2l9kTNRAvziq5+gIFHm8l104bnO2zS4n7JRo=,tag:3lp487QuuMB6SuaJ9u42WA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMjg1MFJyN0VNOElPekFp
            Rm12Z2E1bXJERnptdVo0aXdGYTNLeGF6ZUVvCnJ6c1BaQTFDTUE2Q3dqMklDM29W
            RVlaUmpJam5YR3NqUEQ3K0NGNlJPZ28KLS0tIDR4MitEMXVEQ3dNeHdyb2FtZjg5
            U0Rjd3U2VUxwdXRSQi9OMWtXM3lXMVEKKv+jF0Mg8pqfKQGTaw87WxMVqeJHVYyV
            O+3WJoxx+iHj4W/87mAbagYbrQXfb/EGTqG5zc+txeC2+M5YzLI+0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T13:16:34Z"
    mac: ENC[AES256_GCM,data:60E+BsO75aC8Z8b7izkrC1cwBnwa+GMs3x4t2yarG5OQshX6moza7CaEYpn9SwgYqOSrGHjb9NvtBpdBbkSuLeiz5qJasUguvVf8H7afQgvEQwI14bSNPKOKTWhtkH2XMam/JMgas9l05AL5o0DDyYPsnlIeX28ykft/VwvCFow=,iv:NGG5TQZQd5ah13IAy8ebEXlvyEOh/JONVdh/nFQdh5o=,tag:h4hmp3zGfLCLN/vE6fjuZw==,type:str]
    version: 3.13.1
