apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backrest.yaml
  - whoami.yaml
  - beszel-hub.yaml
  - beszel-agent.yaml
  - it-tools.yaml
  - cullarr.yaml
  - metering-dashboard.yaml
  - actual-budget.yaml
  - vaultwarden.yaml
  - pocket-id.yaml
  - homepage.yaml
configMapGenerator:
  - name: homepage-config
    namespace: homepage
    options:
      disableNameSuffixHash: true
    files:
      - homepage-config/settings.yaml
      - homepage-config/bookmarks.yaml
      - homepage-config/widgets.yaml
      - homepage-config/services.yaml
      - homepage-config/kubernetes.yaml
      - homepage-config/docker.yaml
      - homepage-config/custom.css
      - homepage-config/custom.js
