apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - backrest.yaml
  - backrest-scripts.yaml
  - whoami.yaml
  - beszel-hub.yaml
  - beszel-agent.yaml
  - linkwarden.yaml
