apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: miniflux
  namespace: flux-system
spec:
  interval: 10m
  releaseName: miniflux
  targetNamespace: miniflux
  install:
    createNamespace: true
  chart:
    spec:
      chart: ./k8s/charts/homelab-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    image: ghcr.io/miniflux/miniflux:2.3.1@sha256:42f14382a035e9d9bbc33910ca53f72d47177f75c3c638d2c5a85adf5582d538
    port: 8080
    hostname: miniflux.greedo.net
    resources:
      requests:
        memory: 16Mi
      limits:
        memory: 64Mi
    env:
      BASE_URL: "https://miniflux.greedo.net"
      RUN_MIGRATIONS: "1"
      CREATE_ADMIN: "1"
      ADMIN_USERNAME: "admin"
      TZ: "Europe/Amsterdam"
    existingSecret: miniflux
