apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whoami
  namespace: flux-system
spec:
  interval: 10m
  releaseName: whoami
  targetNamespace: whoami
  install:
    createNamespace: true
  chart:
    spec:
      chart: ./k8s/charts/homelab-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    image: traefik/whoami:v1.11.0@sha256:c2c89736959e8830c3db090e2f54500499ceb0460267f91dce494728d7327770
    port: 80
    hostname: whoami-raspi.greedo.net
    resources:
      requests:
        memory: 8Mi
      limits:
        memory: 32Mi
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 30
      failureThreshold: 3
