apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: glance
  namespace: flux-system
spec:
  releaseName: glance
  targetNamespace: glance
  values:
    image: glanceapp/glance:v0.8.5@sha256:32ab73d80f2b8b5fb0735b0431deb36b93fbb6b2fb43592449b0178c8b83e350
    port: 8080
    hostname: home.greedo.net
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 30
      failureThreshold: 5
    resources:
      requests:
        memory: 64Mi
      limits:
        memory: 128Mi
    existingSecret: glance-secrets
    existingConfigMap: glance-config
    configMountPath: /app/config
    configKeys:
      - glance.yml
    securityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
