apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - glance.yaml
configMapGenerator:
  - name: glance-config
    namespace: glance
    options:
      disableNameSuffixHash: true
    files:
      - glance-config/glance.yml
components:
  - ../../../common/components/helmrelease-defaults
