apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: copyparty
  namespace: flux-system
spec:
  releaseName: copyparty
  targetNamespace: copyparty
  values:
    image: copyparty/ac:1.20.21@sha256:e3ac1088791c79e0911161adfc7bca3fa5134f6596ad16f679754d4f2c6210ef
    port: 3923
    hostname: copyparty.greedo.net
    strategy: Recreate
    middlewares:
      - name: infra-admin-oidc-auth
        namespace: kube-system
    resources:
      requests:
        memory: 64Mi
      limits:
        memory: 512Mi
    livenessProbe:
      httpGet:
        path: /
        port: 3923
      initialDelaySeconds: 15
      periodSeconds: 30
      failureThreshold: 3
    args:
      - -v
      - /w:music:rwmd
      - -e2dsa
      - -a
      - ":"
    env:
      TZ: Africa/Johannesburg
    securityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
    hostPaths:
      - name: music
        hostPath: /mnt/media/music
        mountPath: /w
