apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: beszel-hub
  namespace: flux-system
spec:
  releaseName: beszel-hub
  targetNamespace: beszel
  install:
    createNamespace: false
  values:
    image: henrygd/beszel:0.18.8@sha256:4c51486968efa0b0a702c1b0967966a2e06fb250b7418f3072d2488faea27c51
    port: 8090
    hostname: beszel.raspi.greedo.net
    strategy: Recreate
    resources:
      requests:
        memory: 32Mi
      limits:
        memory: 128Mi
    livenessProbe:
      httpGet:
        path: /
        port: 8090
      initialDelaySeconds: 15
      periodSeconds: 30
      failureThreshold: 3
    env:
      TZ: Africa/Johannesburg
    persistence:
      enabled: true
      size: 1Gi
      mountPath: /beszel_data
    securityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      readOnlyRootFilesystem: true
