apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkwarden
  namespace: flux-system
spec:
  releaseName: linkwarden
  targetNamespace: linkwarden
  values:
    image: ghcr.io/linkwarden/linkwarden:v2.15.1@sha256:7a3cbd1643b1d330ad458466d285527abaab532241ed17b7d6235e7fc93fbcd0
    port: 3000
    hostname: linkwarden.raspi.greedo.net
    strategy: Recreate
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 1536Mi
    readinessProbe:
      httpGet:
        path: /
        port: 3000
      initialDelaySeconds: 30
      periodSeconds: 10
      failureThreshold: 6
    livenessProbe:
      httpGet:
        path: /
        port: 3000
      initialDelaySeconds: 60
      periodSeconds: 30
      failureThreshold: 3
    env:
      NEXTAUTH_URL: "https://linkwarden.raspi.greedo.net/api/v1/auth"
      TZ: "Europe/Amsterdam"
    existingSecret: linkwarden
    persistence:
      enabled: true
      mountPath: /data/data
    securityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
