apiVersion: v1
kind: Secret
metadata:
    name: actual-importer-secrets
    namespace: actual-importer
stringData:
    ACTUAL_PASSWORD: ENC[AES256_GCM,data:GJ97+E4H7cJ2yN/qQzSOXIKgX4vpveAfUkazqtNEK+RyU7s=,iv:TfiUQRn/iBq/FXcZJuk5YZYMQdJwfw/9AZ4cvRECruY=,tag:QnosrRbbg1/YEq8KHXyETA==,type:str]
    ACTUAL_SYNC_ID: ENC[AES256_GCM,data:G+ViQLCathQQYsC5NBVrYlwZpWkAVdra8xwov7ea7D2GRbBE,iv:duZXrmAczRO9HCPgIe6BguI+6vj12dtO7m0cC3ovBvo=,tag:PK2KTcnjd3iJ9m85SJuc5w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2c0Z6RjR2VjQvOXBUck9B
            VXZ0dzNjM2E0a3NEdVBGSFYvM1FCT1ovZEVRCmlhWHBqV3dYU2hkWVdqbmtEZXVt
            VWtydkxoUDRRRjF5NTZCT3pKL1F3TTAKLS0tIDl2WURZQVE5VkR6bVNHUGc5RkMy
            bG1tNWRDU25samIrUjNkT1NHa1hXRkUKoSUQ8FFpDVtyGmSUo1/IlnFz26ZVh3eH
            jI4BB+0r7c1OeqjvHUXfavdxxBBc/pKHMr74O5sbW+7j3C0EN6AK5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T10:08:37Z"
    mac: ENC[AES256_GCM,data:vtOt295eoFRywjbmLEeNfeoQ4adstp/OGqmJOtwFiaVqZcyQbQzNOtqXBDUPx4L1d+dH0YMEu7WTf3VI6Uu6qQb13jRWFwLS5nQuRdOHEyLTyYuC6hV21tQKqJy6ykfBhuSS98HTRKjZTRSzuzbaT7s57CB68RMDI7cP51YcZv0=,iv:cwlsz6TZUvc7Gdgqv6DXnbnuqYFObeu0b15PZacWOgE=,tag:/zKNPfplwSL7E80Kkro/oA==,type:str]
    version: 3.13.3
