apiVersion: v1
kind: Secret
metadata:
    name: actual-importer-secrets
    namespace: actual-importer
stringData:
    ACTUAL_PASSWORD: ENC[AES256_GCM,data:GJ97+E4H7cJ2yN/qQzSOXIKgX4vpveAfUkazqtNEK+RyU7s=,iv:TfiUQRn/iBq/FXcZJuk5YZYMQdJwfw/9AZ4cvRECruY=,tag:QnosrRbbg1/YEq8KHXyETA==,type:str]
    ACTUAL_SYNC_ID: ENC[AES256_GCM,data:vr17jCNxyseGcA2X71R4u2KPB5jYoGBdGjPJ8GgZwWlr2leQ,iv:zl9WTa5oq0dZlFIHrRbcWGAceRtf1j/0fjlegTa7Z7U=,tag:6/zKPEm0YbfyOCfnmV1ehw==,type:str]
    ACTUAL_ENCRYPTION_PASSWORD: ENC[AES256_GCM,data:dcf3lczgLPQNPaXJd5spAJg95nx0kKI5dQPvFaz0,iv:XHID1zC+bnquGeK1CxP+OdZdFS4kc7HeYmzZS8hvBq8=,tag:aneoRDUWTml6mH0nQyfhGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2c0Z6RjR2VjQvOXBUck9B
            VXZ0dzNjM2E0a3NEdVBGSFYvM1FCT1ovZEVRCmlhWHBqV3dYU2hkWVdqbmtEZXVt
            VWtydkxoUDRRRjF5NTZCT3pKL1F3TTAKLS0tIDl2WURZQVE5VkR6bVNHUGc5RkMy
            bG1tNWRDU25samIrUjNkT1NHa1hXRkUKoSUQ8FFpDVtyGmSUo1/IlnFz26ZVh3eH
            jI4BB+0r7c1OeqjvHUXfavdxxBBc/pKHMr74O5sbW+7j3C0EN6AK5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T07:22:19Z"
    mac: ENC[AES256_GCM,data:yZ5ThTZ98gaf5qz6ZRZkM23kyalvF4YLCyeJFC1uYRsct3C18wbMi13uBLAp6QAV/HsMTVaZOHnAD/Asf80xVTrhsn5viy0oPS2Lm/vMHFUy+Eyf/JHaa1PFwvPxcYhq+lai3p7RDj5wEVqc2Tf5I/tQ/Jc66t0nMXJg2Vsdb3k=,iv:JAPyNTGyay8dkH37cww0q3f+AP4QSfjlyJrIBCSYKbA=,tag:jS+x9ELrZ+HsfelMbYHURw==,type:str]
    version: 3.13.3
