apiVersion: v1
kind: Secret
metadata:
    name: actual-importer-secrets
    namespace: actual-importer
stringData:
    ACTUAL_PASSWORD: ENC[AES256_GCM,data:GJ97+E4H7cJ2yN/qQzSOXIKgX4vpveAfUkazqtNEK+RyU7s=,iv:TfiUQRn/iBq/FXcZJuk5YZYMQdJwfw/9AZ4cvRECruY=,tag:QnosrRbbg1/YEq8KHXyETA==,type:str]
    ACTUAL_SYNC_ID: ENC[AES256_GCM,data:G+ViQLCathQQYsC5NBVrYlwZpWkAVdra8xwov7ea7D2GRbBE,iv:duZXrmAczRO9HCPgIe6BguI+6vj12dtO7m0cC3ovBvo=,tag:PK2KTcnjd3iJ9m85SJuc5w==,type:str]
    ACTUAL_ENCRYPTION_PASSWORD: ENC[AES256_GCM,data:dcf3lczgLPQNPaXJd5spAJg95nx0kKI5dQPvFaz0,iv:XHID1zC+bnquGeK1CxP+OdZdFS4kc7HeYmzZS8hvBq8=,tag:aneoRDUWTml6mH0nQyfhGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2c0Z6RjR2VjQvOXBUck9B
            VXZ0dzNjM2E0a3NEdVBGSFYvM1FCT1ovZEVRCmlhWHBqV3dYU2hkWVdqbmtEZXVt
            VWtydkxoUDRRRjF5NTZCT3pKL1F3TTAKLS0tIDl2WURZQVE5VkR6bVNHUGc5RkMy
            bG1tNWRDU25samIrUjNkT1NHa1hXRkUKoSUQ8FFpDVtyGmSUo1/IlnFz26ZVh3eH
            jI4BB+0r7c1OeqjvHUXfavdxxBBc/pKHMr74O5sbW+7j3C0EN6AK5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T07:17:05Z"
    mac: ENC[AES256_GCM,data:hyFyx6U1o0xlRqlGhCb/8pB5v589wXlPLnsTv71pEBSTXsTqIzhL5mjyc9GKdRE+5t1tlnTs93oxSkyoSWbwmHRKiztI9dSVBcanYfHszPOpU6bAe7A3bjZTNvyNZhTLE8Dve0mBzOI+shBVGwayvws2/c/q58PWiKZ0iTb/tpc=,iv:m4uWCG9PB41OYL01VbslEI5H4mzvMBwlYmBSORxdMsw=,tag:/fro5rkwEOVOpE7Bkqyg5g==,type:str]
    version: 3.13.3
