apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:Qdt8FotXvIP0rE8fmjxNkZQ8DGsL5YB/DiWLD89xJYD51IgHeq1YW1J2dcDtgrp9Hix+Xo1LN6lDvhs3dbvIiOndsbm6+/mq83B/1sA2NOd3XFwGHORLaMXOo05uVLT0bgCMxCo9DbQvTQyh80MECZDBlDvvVT10YYY9lRvpAkSh3s09OYCaMItxPw2MJp+FgWuWAJH01zQ486stzaWsDGKUS1dxjOJQUvPcRP45MSaFhJKv8XLcWhK4uG2HFwAKaID/TnG2CSKT3BlS1xONYeaPOpibNCh61ZAJW1eOBmzEBDwSDHl4NA==,iv:7JFTibniBI+NMlnvc+mutTexYbkhLbgcBILnXV0Tx1c=,tag:LlaoiOY5c7cc4qG7m/843A==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: actual-importer
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNUpHVEkwTlF1N3pIM0Fz
            OGVnNU1lUUxNUXF4RFhjbDBMTTRHV2I5RXdvCk05Mktsa1A5MnFZampDTk5uMzg4
            ck9FYnJDaGVXZWx6UUZsUjFQL3JPb3MKLS0tIE0vOG5VUWdIWFI0eXludU9pSE8r
            Q2FtQmVTNko2YVRlRXJoSlNhYm8wemsKOLzYwxaLDP8RQGBkmhMBvIjcAe+qbU6e
            greKmlkegKtnsKaVCL4iWSauu7qyNnuglczjnWrHdw/nM1l0BEGJkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T10:02:29Z"
    mac: ENC[AES256_GCM,data:U84PU2fkQJRN6RYusypm1wJBbC3iVw84k9QKma0tigLSLfpqEDr0fFuRcq4pMNPKtSUunu1TkGzOra9qhRpYzT3K2qrROUGmbWPbf6RPFP2At2PMLDcFldM4pjwKY5ZMr6rgbeZWEqdUophgjdSFezqBQASeWF8Dw7KpC+Sf8YQ=,iv:L8YMnQGvAuRYSH1M6Be0U02i4XLJqWEIpkDQu8oQba8=,tag:hYOBFXTAdvuE3cjh2jw5tw==,type:str]
    version: 3.13.3
