apiVersion: v1
kind: Secret
metadata:
    name: atuin
    namespace: atuin
stringData:
    ATUIN_DB_URI: ENC[AES256_GCM,data:kULpwwbWCfwnlbm6eq3wn8PRMY+AoQJbOb3CGATKbR3Xx8cqDT45TXlk79BQqMmvoE1z0nFF2w8QE5CrBpsftwK4mQ==,iv:fv+6muMPbsxXZAmoumWpSE+l31jF8psSrD2rxfyOjEE=,tag:GmTPhMyWf3ONhDwokFBN7g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOHpabDB3cjBJR0JjYzQ4
            Y2VBVnhpQVJwT1hOY0hqNG1MdERvOUlLZFVjClBBMzZmMGN6eCtnZkt3UGRtUVo0
            Sk9Ja1JQczNhWjlBK1BzT1BiSGxKSkEKLS0tIHVXcTRMNE14eDhiakJwSUUzRjYy
            aEVBcm03enJaZm1OR0pIczk2QmN3bGMKEgriocBwSPbMITCRJrsKkeU4fi1ynfWp
            2xvHTRnINCtW0d6F6VFPNeEKMQG6OGw1gwD81DmQk0Ri1ZVXvXtDWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T14:23:05Z"
    mac: ENC[AES256_GCM,data:icE8qvo7ryEmk86VLDVGOCiLfBDmA25uMkY9c3V/R+1HPdnpsM/D/9tSIFXXTfnNIEqGIAVcQHLApeNMecrEOJOcM2ijN7h6GxtNU+E7mWRRR+/gAfTaR6sBLwo19Qk6O98zEyoC/rLEfJrJ/5pGov/SIrTBADwgjNnL/RbJR1s=,iv:2NsIRHE4YpaA40ikO3iv24vr/omW/p+Vskw9BM2AV5Q=,tag:d5T01457nBEGOL4MUNEIlA==,type:str]
    version: 3.13.1
