apiVersion: v1
kind: Secret
metadata:
    name: atuin
    namespace: atuin
stringData:
    ATUIN_DB_URI: ENC[AES256_GCM,data:x2RZCWRw4lFnKVWfySViDorpCbL7sSFBsJJ/M8ayFPC3NYBSKh3agnPc4fpLXLFVd+CDMQem5+iwSqauQka+dI6j+tTTho65VaWZbjB1doLUFNjVXMbA,iv:0XwHTJ9axhU154MFA030jUJkExVzyCOufGPkZ3AARUM=,tag:RxsUSOr2Zzfr53nG8SHl6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOHpabDB3cjBJR0JjYzQ4
            Y2VBVnhpQVJwT1hOY0hqNG1MdERvOUlLZFVjClBBMzZmMGN6eCtnZkt3UGRtUVo0
            Sk9Ja1JQczNhWjlBK1BzT1BiSGxKSkEKLS0tIHVXcTRMNE14eDhiakJwSUUzRjYy
            aEVBcm03enJaZm1OR0pIczk2QmN3bGMKEgriocBwSPbMITCRJrsKkeU4fi1ynfWp
            2xvHTRnINCtW0d6F6VFPNeEKMQG6OGw1gwD81DmQk0Ri1ZVXvXtDWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T10:24:02Z"
    mac: ENC[AES256_GCM,data:W00Il5I3StseAa9ppXyNAcdVuvHUakdCDpcdUIac+ySqle6iZ87iDZYhcVxpXLvewBxScU2YQ2ZoNl4ymlzYDLNPwIBD6vaHxBQpxKrpL6P8GaargnY/Rg3Uz7+DexOoQhd2bsaQ5N5qkwCmyL0HcMgvzKNZkpi+Sf0bhlwDZdY=,iv:8CQGbgNHBQeDMFRNXLNXBwhzuwAVo6/o8qpzJ4iAg+w=,tag:gMSJ0rP9g30ss95haf49jQ==,type:str]
    version: 3.13.1
