apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:mOBCS3g4k4g65YCzboBr83RAbKGd+MPbUKMn4W/ES7tRG3RL0JVdCfODCcbsCoU6Ph8=,iv:aH/3nMj2npusMoYRUhYY+u02Cf761H1+K8Yc7aBydvU=,tag:nLdPLEZ9KcWCGGOIslCFwA==,type:str]
    AUTHENTIK_LOG_LEVEL: ENC[AES256_GCM,data:qKIGOA==,iv:CdmAdeTeSID98PNUf5iF0yvuYwP+sdJUDXsHgYRdLCg=,tag:6roSSRS1a8dIypQj+flidA==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:ZorLhEur/ixvbGXDs7xkyDJzwTq6cOhKwpROOULVo4Zl6+Awn1ht,iv:AUnAUDEkB9RypEYyIao6dllojHY/eAmYrkY9OVnTKX4=,tag:IeGL3esSeciAA/WcLu1lPQ==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:fjdY7dujzXoH,iv:9MnG4pkA/opElhwCoQiL5OEsrzLYyXXyuRFzPGZYE/Q=,tag:oTE743r+i6cf3ivaCHShPw==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:/nhTzS6bX/Hu,iv:qYlIEwOJ3UPtJFTCTUVr3P+642pabodNlKX8UB3DxrI=,tag:TJLKrXi21LVOUujrQJrfQw==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:SaNGr7/fiGcLSg/K9PRGrFb1p/o=,iv:pCcdi0YpQqFIB5rHds3cWoCcIYn0dCDunrWG3hJ2Z4U=,tag:FeZelnsWqGYnF53d8+NmKQ==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:/XoDBQ==,iv:FANwAC1czBoklNHfEjoxUV9HpBiCMcn3L+mobvdT9KM=,tag:uMfwak1/Ho6uoujXy6234g==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:fc/WJQZ89w4u42q1usUz+UZY3s1BnARtHZHX0FwkKw==,iv:hIvnjYNd4fR/oTkAtQ0cmT6W+nIJP08jYwdDlMqdDLE=,tag:Du6j9P+BOXK6vqFQ3YGgqw==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:H2oH7iRv9DWBfB11Im23EKfk6gYhzV51bzOkRQbn,iv:obNXYj466C7rObbE/TJTFQzu2hnuB3+ycwtxuaN77Ug=,tag:j3WDznegOluIFP+0aHZgJA==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:W/dgk1zOkldujQsXI5lLANMeLGrVDI1hKOBU2rwN,iv:/vEY31XVRuueEVszk7zADPlEuOiKVCFDVOLYAXFyaZ8=,tag:GOdnL93FzgL2DmArcI4liQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZURFL3Qxd3JXQkZFek54
            YU5DY0QwU3ZZRG4wM0pVaDdjaGhiTUpzMmg4CjQyTU5XSmNMT2ZTOTZoUmYvUFJM
            LzJvUjRLL2x0M3UxRUtwYlRpVTJNckUKLS0tIGRUZjJOb2hBRlJYNzcyTytPRDRo
            bkVRMnZORXU1NWhzc1IyOWx4RXU0dVUKvBjGpaT3/BWgoSvgxt6zKbC+G7Yd7jx/
            mtyLBGSe/xNeOh7/72rPrJVFn5CNJDK8qqihQb1clhmt0eD1JXqseA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T11:52:23Z"
    mac: ENC[AES256_GCM,data:+yPmExX5ADzzpS6DxMOAFSOHc96Io2YBM71agHr3+4Tv98tLPo+4RjuODib35pc4eMo1FcL3EKZ39GhA0xO0XTlxK/XTqgZkWRGoFnusyhbFi8uL1htMy/5rOTevsphAu3rpnELF+eFGjM3/wsQwWsm6SmyX0A2Erjgl2GInqXQ=,iv:VSALwpxMJmynoSxP0tSkFre+MYuYzGNeYs+pIT3GSOQ=,tag:gZKTtaGSKXF46/veg5xmZA==,type:str]
    version: 3.13.3
