apiVersion: v1
kind: Secret
metadata:
    name: backrest
    namespace: backrest
stringData:
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:gdHkD7so,iv:5G2e0YiUrVpEUljABrToxo8S9kdTn6/cxzvqvlxO8LM=,tag:BsGjZfQJtJ+Wp78xvbB/tg==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:30qM1/Xo3Vc0wRrBR5DI,iv:oMe4R4h42x7PbwJAUVuaX4yGvld3iE6k4S1Zzygqi+g=,tag:J8Euf0J7xvHu+kT+43OAww==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:sgYOIFHzXfplwo1RtoZZC/8lGBpKceBNxn9RQgdJ5kSrWiAo5JIjmDG6iI3OspfiKBgsV79GlAyj/lQcaaZornan773jy8E8NN8xwjW+d/7+y4ILxAc52CxlNq/3yc6sZ4ClUeeTJaeI2asuzfWghf8v0rMBEz8BTUgw7A==,iv:C8XxUF1SA1Rs3+KrrlMWJKwJa/Cb2WC9UwF9BApgBlw=,tag:0AKCruyTrAdu5LtkpNDz8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOStGZXhHdWFKK2Z1MHpB
            VHVlWHJMYnpuM1BSRG9XS2VhVHhNNTVXT3o0CkFDVVlNb3E4Um9rWENrY29vZGt5
            dGpxMkY3aloyY2JMREZrZ0V0U2k3VmsKLS0tIGk2c08vZThwc3dMU3hvcStjYTUw
            OWhpc3lUOHFJd1pDM2UzcUtQN2hsU1UK7WOSfdKbEo5jog7wvxaiGJxkRqwk+4Fo
            fyhLyJQI1QKoRq+MR+bFMMANzrRcqEhvDPEtIYipYzv/II5Ot+G0ZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T13:49:47Z"
    mac: ENC[AES256_GCM,data:OV69rnm3yyO+n9V11e272b61bn+aREb29tcZYwxRMkj0XbDtohx3Cj5i4bzBWE311VDolPrUZYPf66cAB0+tKAcs+/W2v9M8y53lEwviIYPErgKrAYNCarQiDxACBxtCG1W1nEnN68tC1hQShVRPmGKWMo9ef+H5H25IbMDX0dM=,iv:CsQbza3MiVS8Lt57IFAASJIwA5NwROzAjMTGdUqlVhs=,tag:M4CSUH5aa05H/r986rOdMg==,type:str]
    version: 3.13.1
