apiVersion: v1
kind: Secret
metadata:
    name: backrest
    namespace: backrest
stringData:
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:gdHkD7so,iv:5G2e0YiUrVpEUljABrToxo8S9kdTn6/cxzvqvlxO8LM=,tag:BsGjZfQJtJ+Wp78xvbB/tg==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:30qM1/Xo3Vc0wRrBR5DI,iv:oMe4R4h42x7PbwJAUVuaX4yGvld3iE6k4S1Zzygqi+g=,tag:J8Euf0J7xvHu+kT+43OAww==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:sgYOIFHzXfplwo1RtoZZC/8lGBpKceBNxn9RQgdJ5kSrWiAo5JIjmDG6iI3OspfiKBgsV79GlAyj/lQcaaZornan773jy8E8NN8xwjW+d/7+y4ILxAc52CxlNq/3yc6sZ4ClUeeTJaeI2asuzfWghf8v0rMBEz8BTUgw7A==,iv:C8XxUF1SA1Rs3+KrrlMWJKwJa/Cb2WC9UwF9BApgBlw=,tag:0AKCruyTrAdu5LtkpNDz8g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:OlRH2Ha5P8AIVrwDkB1VdcXhXiBWlPDvLCIaURU=,iv:oxPPzGCBLqnN5HQM6UfCJRAdxu5NTMR9ldWkdgwtt6o=,tag:I0yVkmRBBL1LiSkxFdhjYw==,type:str]
    BACKREST_ADMIN_PASSWORD_BCRYPT: ENC[AES256_GCM,data:BBuuYiJ3bPyeBmiu10+7ZcR6LC3tjDT1MiCYbWBfeU+GU7a3emk9pl9/ZtnR4j57n4+TFLDyYZLU+IUhEynUmsTJmNd2zRXzGOS40eup3W4=,iv:WRI3ptmUAFe6KP/mVeVbkJKqJslm6/RXRZZx6a5umBc=,tag:1/SzGvaKUtHMGVgvGhZLoA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOStGZXhHdWFKK2Z1MHpB
            VHVlWHJMYnpuM1BSRG9XS2VhVHhNNTVXT3o0CkFDVVlNb3E4Um9rWENrY29vZGt5
            dGpxMkY3aloyY2JMREZrZ0V0U2k3VmsKLS0tIGk2c08vZThwc3dMU3hvcStjYTUw
            OWhpc3lUOHFJd1pDM2UzcUtQN2hsU1UK7WOSfdKbEo5jog7wvxaiGJxkRqwk+4Fo
            fyhLyJQI1QKoRq+MR+bFMMANzrRcqEhvDPEtIYipYzv/II5Ot+G0ZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-08T15:16:32Z"
    mac: ENC[AES256_GCM,data:/L8hDu/4DD26sawfsYRzm1+4Pct5Jd8Q2qN8JBDvByzbA307zvhoZGxry8+tSxaIkpJaOolfgn7SV4Q/zciCKF6XrI0R1c4/zlb5WTI9is3xX9ERCiKn7i1kxmivBq9FHkAvAICTNoUfjSDjF0RpFFKgBXq0YDYAAUScmhnb6wE=,iv:c1AtwODXYMJDu5sAAdmnXF0FdN7vT4hAF8J5ivCAIKo=,tag:2E4TCOfz3q2lctMY3KTnHQ==,type:str]
    version: 3.13.1
