apiVersion: v1
kind: Secret
metadata:
    name: backrest
    namespace: backrest
stringData:
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:gdHkD7so,iv:5G2e0YiUrVpEUljABrToxo8S9kdTn6/cxzvqvlxO8LM=,tag:BsGjZfQJtJ+Wp78xvbB/tg==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:30qM1/Xo3Vc0wRrBR5DI,iv:oMe4R4h42x7PbwJAUVuaX4yGvld3iE6k4S1Zzygqi+g=,tag:J8Euf0J7xvHu+kT+43OAww==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:sgYOIFHzXfplwo1RtoZZC/8lGBpKceBNxn9RQgdJ5kSrWiAo5JIjmDG6iI3OspfiKBgsV79GlAyj/lQcaaZornan773jy8E8NN8xwjW+d/7+y4ILxAc52CxlNq/3yc6sZ4ClUeeTJaeI2asuzfWghf8v0rMBEz8BTUgw7A==,iv:C8XxUF1SA1Rs3+KrrlMWJKwJa/Cb2WC9UwF9BApgBlw=,tag:0AKCruyTrAdu5LtkpNDz8g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:OlRH2Ha5P8AIVrwDkB1VdcXhXiBWlPDvLCIaURU=,iv:oxPPzGCBLqnN5HQM6UfCJRAdxu5NTMR9ldWkdgwtt6o=,tag:I0yVkmRBBL1LiSkxFdhjYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOStGZXhHdWFKK2Z1MHpB
            VHVlWHJMYnpuM1BSRG9XS2VhVHhNNTVXT3o0CkFDVVlNb3E4Um9rWENrY29vZGt5
            dGpxMkY3aloyY2JMREZrZ0V0U2k3VmsKLS0tIGk2c08vZThwc3dMU3hvcStjYTUw
            OWhpc3lUOHFJd1pDM2UzcUtQN2hsU1UK7WOSfdKbEo5jog7wvxaiGJxkRqwk+4Fo
            fyhLyJQI1QKoRq+MR+bFMMANzrRcqEhvDPEtIYipYzv/II5Ot+G0ZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T11:07:13Z"
    mac: ENC[AES256_GCM,data:qI04R+Guhy0wWLmmy0pLmYhl2WrXeGbNTA6LXePNmoE8qcSGsry61DO4rju/HhaU3Td3v6n2/AuoCzi83sex/tqDNQGWbpewIIFwMZj175Dqa9oFfGdlcpSZ2ZsBbGFduTrsEr5YoEYEwcwTEPzmYc29zm3VNahL4QXQ54l7tCA=,iv:gUFsbNmXehX8KDx0j8DdIpURdc16ujYWoO21aJ5RlrQ=,tag:+jw9x3dKo3NkIbWSPow8bA==,type:str]
    version: 3.13.1
