apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:hTTDA/Hl72K62qNYSHMwINfepncJiNXDeTYV4y5lq0gXzDslLRrE1w==,iv:x6B9enS3JSTYcuVT7qy+r2iyrGH2a5PBWt98MYd4acM=,tag:x6EYlcEoObaN0bCp6VOtEQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUXVhdys3NzZlcC96RWRw
            SjFMQnVrNGtIQ3Vjd3Y0TDRpbFdwOEN1VEM4CmhyKzU0QWJlNk9LVXZQS3U1eVlD
            STFKd3NBTlFLQVlYcS80eUV0Sm85bGsKLS0tIGpWbGZTSWFWL0hpYm9IUTltQS9X
            QldGektzNHFvOUlLcWkwRGpqQVZiVFUKDN4pp89NS+XHtn8l5jUc/l2/ZjB5Nlw+
            SvuxCS8IEc7DnMRDKbW0eDIkR71HNkNmZ7u9C7IdhuzezYufZMMEiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T20:23:11Z"
    mac: ENC[AES256_GCM,data:dg9HrxpRcrmmjoB6rsKr5gl6mYBjvMLJvkvGJdT82tCMEqDoVlc3AxOQY9HuuGXOCv9oVX6kFwUd1o/BnRRUrCFDJVcga8klGZMq+ihR8Uq+Z2n7RlSkxImLHQrI9tRxzwlD1CNIvHNLB9uNwxxcI+KZ7dl2Ph96My8noKvapYw=,iv:gYnSGimqYDCsHxJWcD3eFBFIJ6hEa7sLSmxvn3ilk64=,tag:TNG4PE0TE/KnOKeHBQojSA==,type:str]
    version: 3.13.1
