apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-keys
    namespace: crowdsec
stringData:
    BOUNCER_KEY_traefik: ENC[AES256_GCM,data:/qpgYgWbKArHXubtYRTF0Fp1HCCgjppnwwBkVRIkywm4xSRou6Cc6YP3OZRHvWDIb+4ZBJUs7Zj01/dA0n4LJg==,iv:+WPZP9sin/bsAEumtHBPbHuQikR72B9mllyRldGFACk=,tag:H79FmIQ64d4t3OhJ0mtJfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcUZDV2E1d2N6Mkt3SlEv
            S1FsTFhqMlhjTWRIME1KeEUwUTlqdUJYaTFnCmExR05BY21TUWtJRW96Slp6SEJS
            SDNwK05VMU0wUGg4dDByaUpVWklYcTQKLS0tIDY3YWNBcHRKM2N6Z3dQdFI0TXFa
            RSt1eUYydkV3bEZJSFJIeC9STzJkekUKuABjrQ6nqyZAf6RwcgDRzLy7T/pYk7LL
            IK+9rhs9wkvAzur6720/6AXq8vb6AEc4R2vhOMdDO4Zof9I+qljLPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T08:56:30Z"
    mac: ENC[AES256_GCM,data:rndyPC73s2GRKvuT9u+ERmBwl5HRueThNqgcGkOIeJGaZ7EFaP7yyF9t1rtSvW1gCdkOh8Q7clPO/qlrefFWZToYTUs4JV7yQqZKaYYSijbvKwe1a/OT9ghPq0Kbg2qmIwEN5Rfityx/7jvdPoBUTmUNU0Wy05DyyJjrZ68tCLU=,iv:UDdbxXgcBQUhqOHxOs0ETau3L1ftKeQBaSuy0rS+zrc=,tag:WFWpWjVJ6tHLa1ZeX2XohA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-bouncer-key
    namespace: flux-system
stringData:
    BOUNCER_KEY_traefik: ENC[AES256_GCM,data:90Vrel0qWHDyo9evcr5USGdiNzK/2Hx+m8jtGnwNPeuNJduV4qWxJ88cWSomYBy7883yHloHbgEK33xXgBC19A==,iv:k+6EJKjFO389ULgs08fe/oMdh8aqxdHfxcDrHqFLdqY=,tag:zpYQ2XTqtGWGL05yhm7LSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcUZDV2E1d2N6Mkt3SlEv
            S1FsTFhqMlhjTWRIME1KeEUwUTlqdUJYaTFnCmExR05BY21TUWtJRW96Slp6SEJS
            SDNwK05VMU0wUGg4dDByaUpVWklYcTQKLS0tIDY3YWNBcHRKM2N6Z3dQdFI0TXFa
            RSt1eUYydkV3bEZJSFJIeC9STzJkekUKuABjrQ6nqyZAf6RwcgDRzLy7T/pYk7LL
            IK+9rhs9wkvAzur6720/6AXq8vb6AEc4R2vhOMdDO4Zof9I+qljLPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T08:56:30Z"
    mac: ENC[AES256_GCM,data:rndyPC73s2GRKvuT9u+ERmBwl5HRueThNqgcGkOIeJGaZ7EFaP7yyF9t1rtSvW1gCdkOh8Q7clPO/qlrefFWZToYTUs4JV7yQqZKaYYSijbvKwe1a/OT9ghPq0Kbg2qmIwEN5Rfityx/7jvdPoBUTmUNU0Wy05DyyJjrZ68tCLU=,iv:UDdbxXgcBQUhqOHxOs0ETau3L1ftKeQBaSuy0rS+zrc=,tag:WFWpWjVJ6tHLa1ZeX2XohA==,type:str]
    version: 3.13.3
