apiVersion: v1
kind: Secret
metadata:
    name: degoog
    namespace: degoog
stringData:
    DEGOOG_SETTINGS_PASSWORDS: ENC[AES256_GCM,data:Dt2p3Oi1Ese2fvmQUzh8LbyP8oPoMrA7hoynMPyhSQ==,iv:yOZNEVmw4OcVpnqVQ1m5CMT5Ko1dcJpKJeczCX6WBhg=,tag:n3+LGNsJQma86V8h3TB21w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMTNuYzdxSVpEci9JTCs1
            ekJ0V24za1pLWXlFNGhKS00zYWFlZWtMUXpVClZYYTBtdk1MMzd1cE1RTHBIcGpa
            SnZQMXhhc3BRSldEcUJIRDhqVXJXV3MKLS0tIGJYVHZRbHZtTTNuQ0drMjBlZTdV
            Nm94NUp4Wlk2WUZydWZFTjFwMCtuUjgKK1tZ7e4a+lSyJILbZxyQS5e0G10Ezwlj
            honoI7vI2jFNBLwjEdXYCQR9C8HyRpnDNS1GQvkeKSAKwOT2AGb/8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T07:11:17Z"
    mac: ENC[AES256_GCM,data:rf2g1gca2Imn7uNCcMmJWAyMVL+tP5nZ58YsDxAo56wVuyVPcPiNoQKDxxMsZhiGcZPMqTaTNa6USYUzZJkPZn45uJeRxnOJbRJL73e2DQlXWGKeysVzhyRRDEOqVqWJIbbIsCIIFZW2qQ8h5CoFM4b85VL8WdwHfoH/YWg0Zok=,iv:TiX+vpxs+tjEo1EjzJcPTTd2mP0MNUMjBzs7+6jqueo=,tag:XyAQ+WAdYHhe7vqafVfTQQ==,type:str]
    version: 3.13.3
