apiVersion: v1
kind: Secret
metadata:
    name: downloads-oidc-auth
    namespace: flux-system
stringData:
    DOWNLOADS_AUTH_CLIENT_ID: ENC[AES256_GCM,data:Kc+86NmBp50vt/UvUGmrASBftOBh8BYuMhGCpCJz81rQ87CU,iv:F7Ir5R24KqqTfKBa5iGS6Yys4V8FFSXezWNrMIxRD2Q=,tag:h1P3EIuM4R/A+Ttyw74Gbg==,type:str]
    DOWNLOADS_AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:81WbJoWFz4lOoY2Tw5f+zhJP39FnJ+VyVyZQyBxNkJY=,iv:vynP38i1QFWBZKLg9k18Ks6JoccU0HjZWA9u12Oc98M=,tag:KCU9FZhXlmwC97LrXWw7eg==,type:str]
    DOWNLOADS_OIDC_SESSION_SECRET: ENC[AES256_GCM,data:ccc9zguj2ZTZsvvOswLlLAGeIKuxEFVJ/N9ytnsC/Wre3VtvIdGRKaTpVkk=,iv:F5J8S+Nc70ims8ycZhF77e46IKWSZUIjPDXBnfXpAZ0=,tag:3xxt3rHn3Yr/FkQhznsxvg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NDVoY0wvNE1DNW9ubkd4
            VW95ZkRhSmdCUTRtampUenM2RkJFSitvRnhRCnJRTGdDamhOUWJXR1FNNDhDRHZL
            Mm9UNFBTTk9NTStDQVE2QUJjWFBDOVkKLS0tIDhxUHhGSjh6N0N5MkxyTUhjTWFa
            Q0xkRlV5cktHbzZVQjNhRE90eVo2M00Kuaw+qFKxSOPMp18XPCwkDfAtpRUQi6fy
            xPz3iFFjyBxnplK5qiDH9jglUd8APLHWEcqnqmDIIHqA48z9bz6nmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T07:44:19Z"
    mac: ENC[AES256_GCM,data:VpEKa/GEh/6opaxE5rE0AFUwzOV/YrS+R+BtUlv80wqx6+edzRQY+Tk0BNyXusmBdT/iFWmQ7M1GRLKCd1Av+gEtqDFlPG3MTkM1TlW0mMUZXyy8OtZCp6bDowEnPoQpSkv0f8eZLLdrHSTrZ26eVMt8UV/8Js3fGCV7VM2RdCw=,iv:HbjPStBy7K6S+bkw/Xd6LR9TGlu7cIRtl1B88COO3bg=,tag:g8QwCRTfFkyrs4h4Qj8NlQ==,type:str]
    version: 3.13.3
