apiVersion: v1
kind: Secret
metadata:
    name: downloads-oidc-auth
    namespace: flux-system
stringData:
    DOWNLOADS_AUTH_CLIENT_ID: ENC[AES256_GCM,data:4C4YWHAyMveNdQeutV9mjMuDD8YfxF22guUrifV1ZHVfF/CY,iv:sChWnSIKD6gpMgpVHIUyq3vt5MXpCILMvR05u6INuSY=,tag:2XOFT8cwL+8TqHS/EB0z9Q==,type:str]
    DOWNLOADS_AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:1dGAl1/XTDg7BAe9Lec+DUXNBxbQTAYMXuomtTquYH0=,iv:TJJqeGRThvsuYDD83t6tTeIcrf0MJpl+RSjYo/5vKzc=,tag:1jkk4qUYfS1TfSmvKFB2Sw==,type:str]
    DOWNLOADS_OIDC_SESSION_SECRET: ENC[AES256_GCM,data:P4fz+53XzBkGqkAax7GDybkLHytEdGMe9Lo6+N+EFec=,iv:8QHzk+iaJgHJC9KicPzvZBEjvDXm3D+sumVZJo7D244=,tag:Eu7G1hAr+7s+u2asAk8ctw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTK0tTTHF3cTZkRUR0SmZi
            cjlKWTIzanNQRkw5NG4zWXVMeWJJYnpESG1rCjFvNFdTNmlZaEtaR3RLdVNlQ1RF
            aUdwOERrMERhNzgvQW1TdzhjZW5ydzQKLS0tIGZaMk5obEhsSXNWNFRtY09raUIv
            TGRHbC83V3VjWTI4dkR0djUvM05aM28K/E++hCv9qlo6iH66YvCDkskSdgv69vsI
            4oBRBzrFiEsApZgeuljBq2gOsC3t4xLrX4AWROczX29kxjYg8akdpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T08:00:46Z"
    mac: ENC[AES256_GCM,data:4dvqO5IgpdSNh5eAddTTpLOu8Au9M6K23I+JyXXaDVlCCRl7iJaxqZMUiPX7BiwkspT7aXnJH+Wn+FCf8DqpeXiXLBO03DpoFKqg0mLGHVgF9joxKm8YPn08AEkxncJhLAlznKOGI9qe3ADYq83zYGm4SPSmK3rh1TeTEKHhBQw=,iv:UU3Li3g5IUDIxOxDnWZ2y9fbkYXUH9LST+kgQWzn7nM=,tag:Z2rINrMhe6SWRA8xkslqSA==,type:str]
    version: 3.13.3
