apiVersion: v1
kind: Secret
metadata:
    name: flux-github
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:yJxzs3lmX/FXo5doJLOzZULNmLBCKlLDIxp/UZ5DzAB1MUKhsuWtnQJTuBONJ7/br+9jeRlIVwS+PQaWPn8q8QdKlwdebsdqGUdrrFfrEmpiqq/mbdG3H0X2oZOB,iv:tl5h21LaZk4s8x276yjQU2TYFLEsVcY10QGoC26BFDU=,tag:quxgj+Bzsj8OPhyyjmQFwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSGhvaGpWR2h6Uk5BMUJx
            cjFBNlZUTU84bm1CKytZZitKVWJhWFpUdVhJClNTY3hINzY1MXJIbmNTZFROMVN6
            NTFOQlMya2JLd2dwSnVMc252V3duNzgKLS0tIFNkdS84eEJtbm1JRnQ4N1M2SVl6
            bnpvL0ozWEtPZ3VIejVPVldtRWJDMEkKazwrLj4qlGav2UiBhRoroPQjzYbLl6ZY
            eisn7qjVUBD2lUcTJUHABBcsvOXKeYTH8kzxLmXzl2P0nIeub3hTBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T07:50:24Z"
    mac: ENC[AES256_GCM,data:x/lrH3P4JK6POgNfqbKqOdPoQOE1FsbgqsXX28wpAi97oekjModF6kz0OWW0mfWr/jey21BiWkrHumt5rltiiX5VmPUObgaiyh0LppomaRYo/+kY+R/JY/sshbw8HS+K2fM1XLiHgDk+Yo/dlx1KFojuqFkABdyDMMLN1NrsncA=,iv:FqaBK6qojU1emBEcplKbfCfWBolQsvz5UpMUposroCk=,tag:cjBNNqrj/mRRcetoaZf8aQ==,type:str]
    version: 3.13.2
