apiVersion: v1
kind: Secret
metadata:
    name: glance-secrets
    namespace: glance
stringData:
    ADGUARD_USERNAME: ENC[AES256_GCM,data:CtRRB4zG,iv:CsCQr6EACBMjddPLCgI5yVe7V3jX2QH6WdAY1PsMNaA=,tag:CkPjhlQXPoxJT6gg9mmZWw==,type:str]
    ADGUARD_PASSWORD: ENC[AES256_GCM,data:D9IrFuvGDVyZQW4xVzFc,iv:EOK4ynlr7DbAdjPMhk7irm7aWJSfNeCIGHHMNH/BNn0=,tag:QRLKWbHZ/0R7j9gOCKNu+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaFhucUlRZE9CdWZYem5z
            OElXM3Y0WFR3ZGNYVDJzaWFVNmVVUXFNa2w0CjVnTGwraGJqTkV4VlByemRQWlhs
            RXFIUmdUdktDQXJLZ3dDcXQ4UWtMeWcKLS0tIEZVWWxzTDFBanFqdzNEZDZUNnQ1
            ZHRLZ0haRDF4d21XNG9GVVA0NXNvL3cKAkxQzgdf3VZbFOw4eoW44bBeD2Ua1yzt
            9bQ2Q+8dC80mfNpb0v8j6QuoEvRFWFmhNPtdzSmiutXNwJJRgTn+Og==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T14:09:29Z"
    mac: ENC[AES256_GCM,data:kapGmu4JNdDrgAjWRp39U7PfTq24iPLKHozy82GsE6TKP03BCXXhwQJLgzyYui/g7pYBSHx8sHqg5OBZCD0EkBBawj5IgKogVjEgdNB8zWMAhjQkkdddyFxEZsmEGNH/ScyPOz+S1RhSZI+LVzyPqit20pNH4ffovAHZ6yScklo=,iv:lkKFE3cx3kdwpH7FEpFPeDFvVj5jl8laA/36mDxJRXs=,tag:sjpg4pcItOZo+FpyalyAow==,type:str]
    version: 3.13.1
