apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc
    namespace: monitoring
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:QbC5nbqCqtlGoIB2t/S3QdjAaEU+6MLkVC/FOaeexcYK5C4O,iv:wTQ1//niWOycwzZn/XO/X36GK/P4ZWo1+PwRDYDoKSk=,tag:lnjy3R3JBneWap+TOlXKVg==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:d+JysqZ+BM9o+ZspjwPYPXWISshyd5w61qjCy318etk=,iv:WAxVqer3qyQHZfvhhNTf/TSvEtYK7ZKYVCFI+NgfNK4=,tag:wiO4An45H5sbv4F5ng+x5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSd3d5N3Vyc3lDVEZncWZ0
            Y09rSzJGcTR6YjhYdE9HdDV1cmduRGtOVHdzCi9GM25HeVlSZlZJMTNnK2V2dXV6
            bzVRN3FRNllRWWRMTE00ZlV5UXRmZ0kKLS0tIHZ2a1V5VEZBeGp1RWgxbzl2NFhE
            OXBYd1FmbTl5NitEbEFsWnc0Zkc1bG8KjNV7pgIMVlMGqW7yl+Ng42Br5wJ27c/e
            3IflNfY910Oor36KOo10kdFOti9nfuPKL7FH9lGqCdvRhdJVIe34lw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T14:27:09Z"
    mac: ENC[AES256_GCM,data:yBsbM+oo1l9RqtCErauIJ2Qof4B+NRWV2353v871I6QSYe+67Yc41g7OrSVhsKCHxsTK7EAl4wGGoVj/9Jjc34fb/mIEP/DZxaOYKUWo11DlJ6XVHEn7PhWSyzKnvPh03Y1ti2jZv9nueQm35FUUHjlHmMjF7G2hDShsEFX2IPw=,iv:PHaY1fbe2VXv5qbMfdlqN41ZnqjcBU8t6yE/S/2IP6A=,tag:c3zTmhLf6zay+eiNyY0E/g==,type:str]
    version: 3.13.2
