apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:Br1otQs=,iv:GYOBQX7gtEw/DKgZzfDA1S9IziOMOQVl5mr3QIBJufA=,tag:3CWimJLAwVy0vfAPQ0fh5g==,type:str]
    admin-password: ENC[AES256_GCM,data:6XDjiYveyaImhBzrN/96OGKoHH4OtUrY18Z5jqIVKns=,iv:OMN9SmLJLNsFo6q5kk690QpmEn9/Q939eLwvnuTQNe8=,tag:/HH137u50DzsQW84pgtZRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQzVrR21wZUYvR0pJQkRj
            bTc0V09yQTJjS0E4Tktla20xcnRCZGhWeUR3CmlFUy82TmxLNjVNOUpBQjYzSzlK
            T3A2OHpTNmpacS9DZ2F2eDhTTFd0RTQKLS0tIGJ3Z2NaVlQ2Y3JyV3pLOUVza3di
            Tjh1Z1cvUzJtVnpVemVjaW40Unp5azQKvPS9z6Z1rLikjfuCYcpISJEpo3NbB/OH
            GET1U2+yOsu1NlYMWdrO0aDc8wS+jOdL+xF/F6ZnFYZs6lSI9nd5ug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T07:58:52Z"
    mac: ENC[AES256_GCM,data:9X3c4DQbLmkV20MuWJDCQKjtBGF/cHOu4rS2c/oVlt/yaYURKwrH+vK9PEFjuzJZRHwVXmbgFEc6kNBe8Q8V/v/mal2RsBwDlYzKY0SyG2aSnyy0YI6gPbP6KRpibjBKOMYIoiQKI6OgxgiSqKC+7N8DgKgGvIbxqP7Sj1XuRkw=,iv:Rp3hrcpk+CsIdIc30WNR1kZN8fZanL2q4FKRvIbHz5E=,tag:OS+mHDHEEkqWN7otM82yhQ==,type:str]
    version: 3.13.1
