apiVersion: v1
kind: Secret
metadata:
    name: household-oidc-auth
    namespace: flux-system
stringData:
    HOUSEHOLD_AUTH_CLIENT_ID: ENC[AES256_GCM,data:ln2myBm9eNcbMReAsAMmQcrlfwpIiALHv8Yu0vDfu8vXdFuG,iv:hBufktyKEHtYxkT+sNmttGxWGIpZPsjfHXqjXvtZ3co=,tag:a1idV4vT1lKcPnjvvDpI2Q==,type:str]
    HOUSEHOLD_AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:cuwIoTSVpmuqk+ED4f1RcRKkagdvCvshgcC2dK2xlLY=,iv:WE8YcLkQEPgJtNbunW6edw+3PCJdwZ3groBAo0rk3Cw=,tag:uRtsu4cjP7f/Xsg4VXIwtg==,type:str]
    HOUSEHOLD_OIDC_SESSION_SECRET: ENC[AES256_GCM,data:buG67in182bKHyJSvClnDF8uwS8qmcPvM4JY9mK/iIc=,iv:gunowU6qytuvjDIvvRALFT7VuvFltLkNiqhyLGqelYw=,tag:SpGWRC8LVn+xlAklHAg9xw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4QnZGVzkzYkhvTXZhdW9T
            YnNJRFg1TG5Zb0hDeUQ2T0JnY09rbzRkQUZFCkRoSnFVdEFRTldmM0NLb2ZXaGlG
            VkFoS3pYSWNnaDgwTGtITmNsUWd5c0UKLS0tIGdmWmlHNGFWMkJpR3Q3Rnc4QnRY
            bWIyREtuSm05OW9HY0IrMkFvU1g4VncKyHyGJT4EvwMuylaFexjpi5B4SPdyWDnF
            V9/AvLJU87CAKZDidTCl63D8CMJ8qPQBnwwUpQGV193uy3DRedEFig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T19:33:14Z"
    mac: ENC[AES256_GCM,data:k3LLMYbfxmaRUEiboJaaK96c6LjAM/mPYTLFksEyUVOJPbCiMeENSBu34AZFyjOJptCU+Qq/F4FzH03G07HfciUU0S2jkzae7sP7BXlsCQClAdHtF9UhZLpY6EhqCXspa07/18dxHcsKO0AwAGPIBuEBHnFSyDB1WNhl+pfHySo=,iv:fNx5pv+cB+HEqXQk85ldyx5qD6aAeZxknd3XwynrjHQ=,tag:Ohi1r1uC8a/UZaLL1K08sQ==,type:str]
    version: 3.13.3
