apiVersion: v1
kind: Secret
metadata:
    name: infra-admin-oidc-auth
    namespace: flux-system
stringData:
    INFRA_ADMIN_AUTH_CLIENT_ID: ENC[AES256_GCM,data:MJSiAQ7ZSNP7/f5z2v+vDQSGq9UErUnRAQsHEhhxdbpOG7qz,iv:0ALXEeSnRGYpQSJVTSRCyw4mhn+Hkel5pDg86fXUnXg=,tag:YAvQPQDMjmZ0Wy7dcNvONw==,type:str]
    INFRA_ADMIN_AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:fJYwCiJO++AzDZV92a/oerf4To87IhjMiSANxsG9kQQ=,iv:HZ9bLRzGf7URQtO/RsmpIeDy+8/l5EIJ0RUhttZ9mdw=,tag:JHL2JkvSiBOlygX6/1gsCA==,type:str]
    INFRA_ADMIN_OIDC_SESSION_SECRET: ENC[AES256_GCM,data:XDeVDB+cIKGl1/YBqcWuoWKYSY2CItHfNNSFw9XuaO8=,iv:NhuD5FSJx9w+q10hD5VDg1Tw+721zLrBCKoeY7VlJ+I=,tag:46/ipKSQuT2I2hxx3UxStw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlOUtPNWdRT0prbFFVejBX
            amRzb0FyZ2VDa21NcVBWZW51YzBOUzQ2Y0FnCko4VlNBRUFUb2F2a2pBTlpsU2JJ
            cDVleDBQMEloNUtKa29IZTUxWnNlaHcKLS0tIFgwUXVmQXVaZ3NSVEFKY2R2OUFL
            cXNvL1JxRkYzQ01EcG5BWDNwUWtQMVkKzqHkkwlRWGiY44nlJQ1lSS4Ct/dHqwnd
            atelkRkbkfcPH5ZRUUfvQbDofZyboEvA+YSVhFWh30MzCoZiqUVglA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T19:33:14Z"
    mac: ENC[AES256_GCM,data:hsX6yiIDa8JU2P/IWPxdH/musLNYsQD4fa1gjb0bTUeYzjCM/5gwJ9lXSSKHMsYhTKV/quaQz/h+wx8zT63tvWEVCm/afcUwlY8ltrr9xFh2JPEXsutU21zTXB/r96cT5IUeQ6m35CotkJp5W+XTJkOXPXGy+qIrq8bAAtzbDvI=,iv:eVaVp+JvTfLmvDFBVCJSrAdrswwSUp0T5HT2b/P1ZvA=,tag:4/H2xjjTqsZCT4zq7akM2A==,type:str]
    version: 3.13.3
