apiVersion: v1
kind: Secret
metadata:
    name: jellystat-secrets
    namespace: jellystat
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:tCSl16VQLJPmMH4Uzg6ColtZR1va8ZVo7Ubbv27HwlgHI8LyI7EkHvwz9l4gJXD0,iv:DhoM2INbZtOojb+jv0WJzcK9Ioh3SZ3tXPrwztrqyhg=,tag:mza8VQDClXIp16KFtn4Krw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:tg7FUZZVd1a9EFVIQpDA7fXKlg1OPwAFAiK7OcyOuoDTIOwuY8DN4PjR/E+nwa5nzYZaMX7OS1VBLITeKmOReA==,iv:DQLpxq7ER47R9I+OsN11KfVsh87ZmFW/q+ur8wCp69E=,tag:Zwfq33EUwANcZKNs4us+lA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdjFzZEJqQzdnZjdtbEM4
            VTROamNNSWVPZk5Sdko1azVPTmVDOWRyT3pBCnh1K0tCb0NRQWpzZ2FjSmJ4N3dw
            TDNZOU9wVWdiYUo0T3N4bzVpSDlES0EKLS0tIHU0T3UzdjBTSklLRzhGUDdZRkJ4
            bHJ6QmRjSjBKTHVwOVRBTXJGM3lxSTgKQcIl2Wa9P88ABK41qfBWHZVn3DA8u6hs
            xthne9OEnq0XKUfd6wvvW5hb+mky4GbiFc/SoYWisWMTqtNmu7K80g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T08:29:22Z"
    mac: ENC[AES256_GCM,data:3Obj3Cofphaf41pQ2rXf7a2bxzNA9MtlLZq9LorSf99z0pbeya5Oxrq/ejCGEI3Z3MoDetDEnZ4HrjJI21QYx0VKC7i3NMo4OmDxPaqLwbXS73CwxPKz/eqPCYZ9JhjGa/S42T/FugxvRXc42MUf1GQsctqskOQHpcXoTt2droM=,iv:psoYvRgB8dVoXlaI/96J1qU8AmPd9WJS5/uJ1Hu1ovA=,tag:+2bL9v5rxxkB/a6W2Qjsug==,type:str]
    version: 3.13.2
