apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare.sops.yaml
  - oidc-auth.sops.yaml
  - backrest.sops.yaml
  - grafana.sops.yaml
  - grafana-oidc.sops.yaml
  - cullarr.sops.yaml
  - glance.sops.yaml
  - metering.sops.yaml
  - pocket-id.sops.yaml
  - atuin.sops.yaml
  - proxmox-ca.sops.yaml
  - jellystat.sops.yaml
  - flux-github.sops.yaml
