apiVersion: v1
kind: Secret
metadata:
    name: metering-secrets
    namespace: metering
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:19dpgLJGlD0bemZJ1gFakBKSKxHgLHrI09wg,iv:ay7kSia75uRmJzS5XpuX4aF9CrAsOjqL0mrrBtGUt18=,tag:0XJiRnQBWociCnp8MgQZSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSGFSNk1jZWxKMFFiOEF6
            K1BKWEx6WDhTemV6d05UcVhOanB0VWpjM1FvCkp4RWhUU21sRkdabUtiM09ISWxR
            TlhwMmVHcGh2WG5kcGV3SGZ3d1NwOE0KLS0tIHExVnhxbEloMk9mQkR3YWNFSGMx
            aUt4WEVxVzlPVStHSkN2UnNzemV4Mm8KJomudf+YEgSCU32loFrm15ad/TpRhmWX
            y7TjONrcFk4NqSOOx8aA3EySU2VGmwOJIeL9BYRt3Tfljd5bWFCYPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T13:54:20Z"
    mac: ENC[AES256_GCM,data:iDf9YSFYg1XD4yL/hlZoos5MpFJliPeSMgxkNjQ6xP+THYWEsv28s7l3KWVCRTJMV6JSClP3uqoWZE0Xc7QxfMyu7akUVZS4XWwQNpK8tJqNZSPqtMJkGmsfaW9Rc3poySg/YC4/l9WT638/viJy4xHRsSy16S5VCqRSYiq5juQ=,iv:E9XZLPWNhRUHpR12OrAg2yQ6k53PiA0QODHrqh85ZJo=,tag:CdgDuvhJsXIqcQihEila2Q==,type:str]
    version: 3.13.1
