apiVersion: v1
kind: Secret
metadata:
    name: oidc-bypass
    namespace: flux-system
stringData:
    OIDC_BYPASS_HEADER_SECRET: ENC[AES256_GCM,data:uNUgTL2W98AhOXMpriq0P7mtbuO8izdK8ZF95BM2pLd/9KaiADGf1+yiMImJ9SsFbr5Hyt5h4/CLMxa9tftIJA==,iv:2fG5EYs03QuHA1TlPSPwquthh60RAFnULXWDjrdEdLg=,tag:49iWcECwMvobcMdL8jeOXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZmUrUldLWndzMlM5b3Ez
            Qk5pdWtrWnJldXAyM3ZGRjVsUlBmUm9kaDIwClZPa3pZT2ljaUFzTnFNOERHa00x
            MlQ0QnJMaElIRno5V2NydlF2RHlQeGsKLS0tIDRQTTFHQnNnWTlpbUxmejVVbUZp
            QXR2Q2dFcGRONGc5cjAzVWhsVFJVQjAKXqbaBi/P8una/lJtEhjqyGRILW4K8UOE
            F8O3zg/irHj1dtmJ8Gjufcz+dLggHH4B0dyhwg+22SXVW+62p1Lqcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T09:25:22Z"
    mac: ENC[AES256_GCM,data:KxU52AQjTcePuNHKa6SExNO7D2gSiwPRhqdt3XlB3rWuN6IQd7YWD6VWOY4b0cxUTnnIZOX1hvtvkvrQuzqP+xvUZVmkYR61CODtgpXwdpLCV6UT6TXUxl1E5SITVqAyKik72xIE6TNu+V01cj9NlAnGNCYVDsD6Ff5O5NROT6g=,iv:3GhUswZxnxy5FQ9BWNzEDVRdAvUN4rVO7RJdKIpP2sM=,tag:3qBm+li+wTfkFg0YGXdpJA==,type:str]
    version: 3.13.3
