apiVersion: v1
kind: Secret
metadata:
    name: oidc-auth
    namespace: flux-system
stringData:
    AUTH_CLIENT_ID: ENC[AES256_GCM,data:SlAJzSEni/VgL1GQg6u64G0XxyBXUwH83EPJvCQnznw4poV4,iv:A+pRFtKQjpoZXRDDArd+Qp9TyQVTyL9VXpoZiOE48UM=,tag:ilJaMlA+KPgWRL/64RwLgg==,type:str]
    AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:NqfU8ATeDDQZXAAI+xKBTW0NNKw2G3+i0SE9xro/s3U=,iv:HSEQTEgs0nFLGzb9CS5ZcbeetUXUY9F2f08QQIbNDW8=,tag:yxhwVYKsIH6S6FdSwrvAEg==,type:str]
    OIDC_SESSION_SECRET: ENC[AES256_GCM,data:ERYOc0T8iyCU746D0LChNs/u1ibmEUOmS9/WLAELJaw=,iv:QL04XZi9EuMHqm8U1yplaxqEODmJkOh0CrOxLutx5hY=,tag:QIuq4YCaHb+bD8z+w/jihg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbDZoTG16My9nMnNHK2Y1
            R2ZHMThDWFNZZ1Y1ZXlHVEtxR1JLZ2ZORGhjCklQd0huM0dTM2ZIcEJlM1hYZnVk
            ejRZakdmNmsvckRxRzZCazJnYXJQeXcKLS0tIGpnajh3L3hNRVl2V0VsRkdHYnZP
            UXI1UVlTTUhlUmVYWUZiZXU1R0NQdjAKN33SMo50as3ZDzFBxKGfDsCPWzEDkc7U
            LHNpKWNmMjHzxjJ5BKRXjY1+/Rxx+nIvinZg8aWnALIlQwD8e/3WNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T14:27:32Z"
    mac: ENC[AES256_GCM,data:quWG/2KYdzDsbCzX5e18P76xQmPtWHQ6UtMF/ZDNuKbqudRWFJC3+C5qYutHknKjSf1tsbFkur/R4yn+XtLvqawhaGgmaCA2vC2zG6g44xae2gCdQ6fId/9WtRurE9SpdmJ2R2uzoCo95Km84tel7+Jg0CnrpTgtxcT9KiSCIMA=,iv:9wNka09xF130u+wWBC0AdGilOk2QqExA15VDPT9Resc=,tag:oI1QrPVsttBk/fNJ8Toarg==,type:str]
    version: 3.13.1
