apiVersion: v1
kind: Secret
metadata:
    name: order-pipeline-dlq-processor-postgres
    namespace: order-pipeline
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:EAFpMdBLP54xG6YSn9rWCaWV6vLLooXQiLdYpy8Mz1c=,iv:Tgh3ArnBMJM7Ur/pwArCHtAAu4SUqspd/ZMbx022FR8=,tag:t4PEnkfqqW/cRrwnjzwtKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdDAyNUdLNUpaVTYweW40
            ZUNQbGRVUlNmR0xuR3MzTVhqdjhlUVU3b0hVCkRocGJTeVBkZ3lJYVhwb2ROYWdi
            bC9oNjJ4eFI4eHIxYkhsOXFMTUxob2cKLS0tIGFBVUpWMGFaVzUxZUxQc2FYMGVZ
            RGYyNGkvYytkU3Vyc0U3VFBOREN5RTAKU6OtJvCPOdNAzKts8au7hlIW7/3+u0V9
            kcHOQTfi/GQ9HjFzhrIKcJHmGiPjliIjJgzkUBS8yF4cDtssUBB1tw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T19:21:31Z"
    mac: ENC[AES256_GCM,data:N+vdwQxT32q0E/UK4b+opeQzcMEvC5xjVbAIroB2vujyiBdDT9wh8FitTJ1D1nCH+AVlXEF6YxsSEYCWd/zLQqd1SZAp9FLzvnIDb5E92r0TiCXd+HZioiO6juKwlpiE8d0l1qxHccPR/UMoBjblBq5o4RcAsCZUU1EDEdRkBdI=,iv:iR67Qu6ZtCMJRGHMb1/k0kpnQQeCyB3dauz7CuRnREo=,tag:bd+zeaTMBICkCFh7dtN8eA==,type:str]
    version: 3.13.3
