apiVersion: v1
kind: Secret
metadata:
    name: order-pipeline-shipping-postgres
    namespace: order-pipeline
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:CVXd+w3oQMZA6Z/QTTLh1dlIoqkog9GPGXqEdjnSx9k=,iv:bKweoAvXr2i/kn0V8b/uEIRbGICqtyBI2Fc8dDDj+AY=,tag:wJVUG9hyXJHgqK6jzvu/4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNnlpWlJpaDMyejIyMGls
            MGFDUlNyekR4SGx5aGxlR3RmTDY1bE5YWlRNCjNwaXhzaXVJcDdTT3ZMY0svUmxo
            cjQzc3dFK3VVY3pOQU5Sa0p2TGpaVGsKLS0tIGx0WTl5Rm5tZW9abXVvbU1CYTNJ
            Mzc4ai9lK0UxYkpEWTE2bGE5SFNadkkK98QspEsSIM9KwOKjp0Z++LJtdfctYDd/
            +Sk2Y6nwYCIQrneMn1Ovga6vumAbIpqwX0m+XTv73BztzO/iHhGopA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T12:46:15Z"
    mac: ENC[AES256_GCM,data:9uvSx0gSLd+ZfM5YYVNYpz+jUlvGvULEWmzyctCsWI9bzaJnBLTwCES1K81mSX8k+nekSVY/meZ6hqfqzEZiRvILdbxV//xTHUKtUtuqV9tIfmqkzT3370iXlFFLOyopuzpcS19DJkKGQ/F94XrP4ShkEQsRhejgoWr3i6uqfi8=,iv:arNcL7FJNYAkDD5yHM9b1dREhh/3LAQowL0dAGlPafg=,tag:Kt+xgaEydIbfrwvPqswWuA==,type:str]
    version: 3.13.3
