apiVersion: v1
kind: Secret
metadata:
    name: order-pipeline-inventory-postgres
    namespace: order-pipeline
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Wq9EGaJFl+anpkWCPst1Hy+PKVxvgkFVKjoX7O03Brk=,iv:clMkNMURYEfiLouO4JJZzk4em1+5b8mqHv7lH4pqy6k=,tag:P0thKZaYR2UpI4nCnVKPNg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SWg0RUc5NFltelZIREVn
            NmZUdThkUjk0eUVta281UEZ0UHE1RGU5Y0JRCk9LMXp4aVFVMUgyWGcvVWtNcE9F
            Kzh2Z2g3bll2RE42SmdoLzFKVXcrLzAKLS0tIDA1OVN1YytuNXlGWVBzTmptbE9p
            K0pNUDVxejJvMUFUMVJRdGNtUjZ2eEEKK4LCNlEjQtyb78Y2ltX6M8vBjUTGu61X
            Nt8rdjc57O1RNViiDf0O/KzgLzTE34Wi/JPPTnn1hvFL73XKG4Jq6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T12:46:15Z"
    mac: ENC[AES256_GCM,data:YZEyf/KOQc0QG8paNO5Gi1P2IhL7X7JdD9LNYp6FbF/Cwy1Mxbhzu8wem/+1p5X1oXwdqqUbQs/i3no3v2Tipvki9ceFvbJ0PLdfhOOQr6cASpI4ENi1JNE0YgeOcGh0lVOjLKllFBZ70ogPfPguMY1QV8+qb9RDUkLRwdIo7n0=,iv:ldN/V25dZ+SQtFHqyjJ9Vna/JYRuIJ2RIUJ5Aglsi3o=,tag:n625QuTARXLF7KemqHYVxg==,type:str]
    version: 3.13.3
