apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:SS41XqvRHKM/0K9N6qq9UzXIfH6WxD6RpM/ACNtKc0L/qcx/ESi/zI1EtQD6EIQdltwqPHCD3z1vBqOd+gz23cjBQB6OLFmGUypjV9/oXL9kde62RfM0yHYo/4JrxOmiylEpi4P2GXsw861p6ONllGMul7ueDHhVbgKaYgupR1o9NzUZHnoXvD1oAbwDBdmSp35UoZ1E0BydyJ1Z7lAXvZIjHzDQ1NwknMTLkzkPW8lpY7Qrk7gGxoG97ORiqHvRoGAd3emzS16GBkCJznHraByugnIsAGImbvLH/veCvRCJ89JHVY7+BA==,iv:I2wpJC11CRKCV149ErF/XfY9VoNlbU/68r/mHaWWmMc=,tag:vcffnRugVKD+QgumClNKyw==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: order-pipeline
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyS1piWVFpMmdZNzJSVmp0
            WmpMNmZBUStVMUp3ei8wVVRXb25TN2FESzFjCnFKVnRweGJyay9rQm8wdnBsOGNr
            YXhxeEVrNThuNmFvMXRrU1pNak9sWnMKLS0tIEF1bzJRZkZKQ2FDNzc2WlhxUHFV
            Zi92Ym1VZ0dreDU5VXJMUlRkc2JpWmMKe2sPh+k9AWHgReV/LBIvn+8M+Ks6Gxlv
            wOYJmvQb1EHA7tLHMVEwfWXD31cjanuCd5Lfx5RlBN8pft1JVHrhNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T19:37:31Z"
    mac: ENC[AES256_GCM,data:5YeUsfgD+r2vlQZhNN7y2tQfXxAAnFXM7mv8/Y62IXbc5iURVX91HIsPXeg2y4weuUusyuLR8fnwBAzhHsVOeZdc87hBZmchgpyKcRYZgsYMWgwwPFMeu1PNB4bQsaGsvpAoMauJeEt9BTmi5MBWGuDuykuYVRBrJs6otzrDdKM=,iv:zEBV36RFhZKjSzllU7Ocvwyv7Nzlsy/ALNSOFtvehjg=,tag:4pGY/f8iUOvYPESnfLkN2g==,type:str]
    version: 3.13.3
