apiVersion: v1
kind: Secret
metadata:
    name: order-pipeline-notification-postgres
    namespace: order-pipeline
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:UPzSNfbNgM+ZYCC9ExyMmU1ShHbVqpTlQrR6gsKVdRo=,iv:iuGtqzc3nTwr5StbvtGimfexrKk3KR5+TZ56aLguovU=,tag:4tFyO6DB+n2ELdefv8VAYQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUjM3RGhtVHdQL1dXNGtW
            NWUxYVZXajNiZDhCYzZveCtvK2tneGhjU2pBCnBJTDdVMUhxTlN6NEtxM2FEd2Zm
            WWlqdkUwaVUrSnhmUHdYVE9xRXBBTUUKLS0tIHlvSFVBanpielBYMk9PUEtMRWd3
            L2k5TWJGMTQ5STlMTUw1YTEwcUgzMjAKeumsjhdT/BfeV1VFBblwUwg3T5CmKIdX
            oPCy149DfcX97I+hRyjDuShOnFMuw+LdAYj3iVmwJRbuTSwyYrUnDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T12:46:15Z"
    mac: ENC[AES256_GCM,data:giT7OTONij81DAgn92ru8s1fTU7jYTtgHnROEUmonPYybvx+uvAPa4j+6iZjg5aq+3+3B9wvz6+rmswJfvD1A9FHvSWI7cZqd+B44OdH+hv2o/MWxp7ph1S9qVL0WDob/968vlENw2UCqEXcQfKn1YD2ntgQtIgdby55/VDcyfE=,iv:DtOZZbBvBK0JLoP/rWu7SaSYMKZimDKY6AG09tHZsGE=,tag:EzacxBAthGKT+8YHSUzuNw==,type:str]
    version: 3.13.3
