apiVersion: v1
kind: Secret
metadata:
    name: personal-oidc-auth
    namespace: flux-system
stringData:
    PERSONAL_AUTH_CLIENT_ID: ENC[AES256_GCM,data:I/pUCuxdQy5wAboOusvNV0hf3NvbhQkSq2c3PzOjb+lI9aC1,iv:7MlQGS70AZnswzU5ttEtDvNfWous8Vcd7VsBGWI1pJo=,tag:Xi7fmzXazAJz5gr16q0iJg==,type:str]
    PERSONAL_AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:QbmeYV1g2vahyK/fkjO+U9/UX6xecuUfZ2NbaRCef9+kR0dvezOU,iv:0MRoO35vP+OxYe3pz55326vaypafX+kGI3m/9YuqryY=,tag:sHLAjHo9rgVB7kiHrdNWZg==,type:str]
    PERSONAL_OIDC_SESSION_SECRET: ENC[AES256_GCM,data:SWoRtsOTCBoR7BnpllBouMXrME/ObI03PvCkn1927fQPgxNRazsFOABYizc=,iv:Gh+VZrzyxs0jbJcb3d7KXSVd2bq0QAtTZSEh0Cwc3P4=,tag:xe0oTUuJJj62TUGSCDBRMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMDB3VFlLY092MHV5UTRE
            Vm45S2E3RVlaOXRBNGNzM29vWTEvbWx2ZmlZCk9JUjA5SWptcWl2MFFVQmN0eFNa
            eUNOV2lrK0dQOVJaamtWbTlUV1l1V1UKLS0tIHU0VjFmOUV4YjhRVG1tQksrNDBF
            a21aOEdSbzU3eVhtY29Tc2svRjl3azQKYZWXkaYv3lFjSfcUrNnJ7Lad9s2t+fq4
            7aVOTjJ2KC4PY0/oNCl/77l45YVeWHHTRresTKOGWX0ETnfB+Il6LA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T18:02:45Z"
    mac: ENC[AES256_GCM,data:Do0RjpnUJ4Ipcgu5jxl7EChpf56ymP47yZlx3qwEUhldnB0w+iICrtxk2RWR/YiiY0KAigA5m1yWPE3gQSj6eodDIvupB4vzGi1f5tVFolTfdr7IZUsR8x86U25W8CnOQ1ZRW25863NHy4guyS1OCMCoc87T/53edct1r1WRD6s=,iv:/kr+/vSFc5sWxAql1mvxn7OyYQQ8xP2KtYO3STh4jPc=,tag:DghBdB/IoA6EAOdL4F/WIA==,type:str]
    version: 3.13.3
