apiVersion: v1
kind: Secret
metadata:
    name: personal-oidc-auth
    namespace: flux-system
stringData:
    PERSONAL_AUTH_CLIENT_ID: ENC[AES256_GCM,data:I/pUCuxdQy5wAboOusvNV0hf3NvbhQkSq2c3PzOjb+lI9aC1,iv:7MlQGS70AZnswzU5ttEtDvNfWous8Vcd7VsBGWI1pJo=,tag:Xi7fmzXazAJz5gr16q0iJg==,type:str]
    PERSONAL_AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:QbmeYV1g2vahyK/fkjO+U9/UX6xecuUfZ2NbaRCef9+kR0dvezOU,iv:0MRoO35vP+OxYe3pz55326vaypafX+kGI3m/9YuqryY=,tag:sHLAjHo9rgVB7kiHrdNWZg==,type:str]
    PERSONAL_OIDC_SESSION_SECRET: ENC[AES256_GCM,data:FGe9ODjLiyk95sv71ZAuqnWf+Tpgxrl3aPR6NMBZE9s=,iv:X4YFauUJ9NfkAROFZGxqTIqG/CjCH84YbcJx2uw4n4A=,tag:iUCPYyba0DEOrsMGnYFbMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMDB3VFlLY092MHV5UTRE
            Vm45S2E3RVlaOXRBNGNzM29vWTEvbWx2ZmlZCk9JUjA5SWptcWl2MFFVQmN0eFNa
            eUNOV2lrK0dQOVJaamtWbTlUV1l1V1UKLS0tIHU0VjFmOUV4YjhRVG1tQksrNDBF
            a21aOEdSbzU3eVhtY29Tc2svRjl3azQKYZWXkaYv3lFjSfcUrNnJ7Lad9s2t+fq4
            7aVOTjJ2KC4PY0/oNCl/77l45YVeWHHTRresTKOGWX0ETnfB+Il6LA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T08:11:04Z"
    mac: ENC[AES256_GCM,data:HFZKeaq12VKd06FK7kp9zI+6DaxveF0+LVnEPMOAOf4ioiMXJBCcP8tbS9qZRx5lBipwQFVocSr3OiidtuY17LSH2UmsP1g8Rxpb+xVcaN+C0Z0OoyJ+7WBSZOtbCBx+s9wDGEypg3YuYJCV+4z85uYfnxPsxkahYPmkBlTCA4c=,iv:N56gJAcXuOy91LFplgDa/jXMza2BsvSqnPMHGTSPlOE=,tag:H+lfdDkveF06vtGHjHEa6w==,type:str]
    version: 3.13.3
