apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secrets
    namespace: pocket-id
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:RZuCS2XJ3rXsqr1itwe4/wvfV0m+7eSgP2ljGWjPQw/BsZW+0hN5w20VG+4=,iv:yqnTV5fabBtD6K1MpAPNZmR6hKAxBtOcTYBdzWHtrsY=,tag:bg0H7lgmrbt59x6MVilXxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Z2FQR01sdHZra2E3UHp3
            eVRnSmFxOXpFQUpHNTY0MnYzUjdzYUFXbmpRCnJsazVqMmRhOThTV3NzNUhJNkhk
            TFlIWVF1UHJHTDIvcG80dy9MOGhCT0EKLS0tIGJrM1I5NjlzU0pqN056dDg3MFVj
            NklQZFFDek5wRUo1eWxTR0tDN2VPU0EKqwL5uAjNWtc2nv9Lw1fljjdVhkSwj5Lr
            n5M4E34qZe1F86tGklwuctn2uR5lTu68xBnCS9LQPaFCSkOJFdP2yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T11:16:39Z"
    mac: ENC[AES256_GCM,data:QkasdzMoka4jITBjzLgvBwaIlmmEBboNOsCPGfcDcTIBOt+RNWHvfpspNJSFE7km0uS6PgrUf1XrC81sDkQevJMRkRpVueWskUI97BCyZuSy7s1von2auA/xnJobHYCtL+pKCukjweBW0N0FhMxsF1ikl/C8uTnuJ+NBFVMhvao=,iv:sNpG4TpYPrJM6+CQK9mCV/CpTjebatNSyQCeU6gw9Zw=,tag:lAmnt6uUdfv2ypnUqn12cg==,type:str]
    version: 3.13.1
