apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secrets
    namespace: pocket-id
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:mH47kuOw8L0yT5XvWsHrNkW4iTuddc4XUyQs85sx7Pic9UoKcpQhsZN6Xhk=,iv:kPvQBAPkdhEGTortEWDU8MCAKDQOhdwhiYlJNT/MWzA=,tag:36k645V+c2UGQgIpG7ryRQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Z2FQR01sdHZra2E3UHp3
            eVRnSmFxOXpFQUpHNTY0MnYzUjdzYUFXbmpRCnJsazVqMmRhOThTV3NzNUhJNkhk
            TFlIWVF1UHJHTDIvcG80dy9MOGhCT0EKLS0tIGJrM1I5NjlzU0pqN056dDg3MFVj
            NklQZFFDek5wRUo1eWxTR0tDN2VPU0EKqwL5uAjNWtc2nv9Lw1fljjdVhkSwj5Lr
            n5M4E34qZe1F86tGklwuctn2uR5lTu68xBnCS9LQPaFCSkOJFdP2yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T11:49:29Z"
    mac: ENC[AES256_GCM,data:3Su8Gpoxg18slx6JGGdt5ko/q+1zP/6j4k+Q8W6yOnPyt20gJJfZQ+qJ5IdRBuhv38ecSEph8t2/EYm5b2tPZv7VkEJlAFlzarcmwbsrKUnPqkuZsZLqOE6IZ5zRR0FoYv7YwMeEojF/Aum0LZqtu2G1rEWYC1GRaXepFSURSAw=,iv:quntDn5Zxg0b6vkWj6h0quTR6dX24eUIbSRrRWMQu3A=,tag:P/139SY5PANHwzkWaDSh4Q==,type:str]
    version: 3.13.1
