apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secrets
    namespace: pocket-id
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:J+87MGgu+s7EvWrdHDBYACfenikKDJfXNjfBj9WUefzWVylmvKm6pvygMho=,iv:nE4BYx7eE6xFOAhGT0ZgQMSqf3UjNXj7ZVuDNwa/ziY=,tag:JcLzn3eclt+E1D76NR2VJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Z2FQR01sdHZra2E3UHp3
            eVRnSmFxOXpFQUpHNTY0MnYzUjdzYUFXbmpRCnJsazVqMmRhOThTV3NzNUhJNkhk
            TFlIWVF1UHJHTDIvcG80dy9MOGhCT0EKLS0tIGJrM1I5NjlzU0pqN056dDg3MFVj
            NklQZFFDek5wRUo1eWxTR0tDN2VPU0EKqwL5uAjNWtc2nv9Lw1fljjdVhkSwj5Lr
            n5M4E34qZe1F86tGklwuctn2uR5lTu68xBnCS9LQPaFCSkOJFdP2yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqgftl7xwtdmpwmsazp5xerqrq4wp3aljpp0a6qe5ewg0cvs5yxs6gdlkl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T08:42:14Z"
    mac: ENC[AES256_GCM,data:ZeJLiaSqKdx4FCxq8HvJXDMMehunfi9CEQI/MjngT0F+cjpBJ5ZI/iYBblmcBMpqiJk1Yiu81YgOXrMaiCiFve4DiCN62TizTl0P2NDK5IC+TeBxpMGV4dkLM/RNyEEbuSmEzxCj//37j6q/JfkFXYVQErLRxm7IcSm9MmV1BoI=,iv:S/UR81jhBrO3CG+umQ09liehUYpYJpCJroECbdVA7pM=,tag:0bb+NHgC+j6IOgrvoj5qrg==,type:str]
    version: 3.13.1
