name: Pulumi Preview PR
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'
      - run: go mod download
      - uses: webfactory/ssh-agent@v0.9.1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
