name: Trivy config scan

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  misconfig:
    name: Misconfig scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Trivy misconfig scan
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: config
          scan-ref: k8s/
          severity: HIGH,CRITICAL
          exit-code: 0
          format: sarif
          output: trivy-results.sarif
          trivyignores: .trivyignore.yaml
          version: v0.71.2
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        if: always()
        with:
          sarif_file: trivy-results.sarif
