name: TruffleHog

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  scan:
    name: Secret scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@005b692bdfd0764e5da402887d9ab9196f8023dc # v3.99.1
        with:
          extra_args: --results=verified,unknown
